### ISSUE TITLE
aggregate function for hyperloglog

### ISSUE THREAD

**Issue by mdespriee** [timescale/timescaledb-toolkit#144]
## What's the functionality you would like to add ##
An aggregate function to merge (union) several hll, similar to uddsketch(sketch)

## How would the function be used ##
Compute hll at a certain granularity in a continuous aggregate, say hourly, then be able to compute a approximate distinct count over a much larger period, by aggregating all hll together and calling the count()

## Why should this feature be added?  ##
see above

### What scale is this useful at? ###
large

## Drawbacks ##
A massive merging of hlls can saturate them and the error in the count would skyrocket. But this is more a matter of documenting properly the dimensioning the hll in the first place.

**Comment by JLockerman** [comment]
We're in the process of updating our HLL implementation to a HLL++ one; we'll add this functionality when we do that merge.
