### ISSUE TITLE
timevector broken for compressed chunks

### ISSUE THREAD

**Issue by ericcoulthard** [timescale/timescaledb-toolkit#279]
**Relevant system information:**
 - OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]
SMP Debian 4.19.208-1 (2021-09-29)

 - PostgreSQL version (output of `SELECT version();`): [e.g. 12.0, 13.2, etc]
PostgreSQL 13.4 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

 - TimescaleDB Toolkit version (output of `\dx timescaledb_toolkit` in `psql`): [e.g. 1.0.0]
1.4

 - Installation method: [e.g., "Timescale Forge", "docker", "source"]
source

**Describe the bug**

Getting an error from using the timevector function on compressed chunks. If I don't use compression or if I SET max_parallel_workers_per_gather=0; the error goes away.

**To Reproduce**
1. Create a data table.
create table public.data
(
    device_id  int not null,
    ts timestamptz not null,
    val      numeric(12,5)
);

SELECT create_hypertable('data',
    'ts',
    'device_id',
    1,
    chunk_time_interval => INTERVAL '2 day',
    if_not_exists => TRUE);

ALTER TABLE data SET (
    timescaledb.compress,
    timescaledb.compress_orderby = 'ts DESC',
    timescaledb.compress_segmentby = 'device_id');

SELECT add_compression_policy('data', INTERVAL '2d');

2. Run this query

set search_path to toolkit_experimental, extensions, public; --still experimental, so do this to make it easier to read

SELECT device_id, timevector(ts, val)
FROM data
GROUP BY device_id;

[XX000] ERROR: serialization error Bincode can only encode sequences and maps that have a knowable size ahead of time Where: extension/src/time_series.rs:213:5

**Expected behavior**
I expect a list of device_id's and timevectors.

**Actual behavior**
An error happened.

**Comment by davidkohn88** [comment]
This should be fixed in 1.3.1 let us know if there are still problems.
