### ISSUE TITLE
Unable to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by zhiyong80** [timescale/timescaledb-toolkit#291]
**Relevant system information:**
 - OS: Ubuntu 20.04 Desktop
 - PostgreSQL version: 13.4 (Ubuntu 13.4-4.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
 - TimescaleDB Toolkit version: 1.4
 - Installation method: source

**Describe the bug**
Hi,

I followed the installation instruction described in the following page, but could not complete all the steps.
https://github.com/timescale/timescaledb-toolkit
When I run those steps as a non-privileged user, I had trouble at the last step:
```
cargo pgx install --release
building extension with features `pg13`
"cargo" "build" "--release" "--features" "pg13" "--no-default-features"
    Finished release [optimized + debuginfo] target(s) in 0.33s

installing extension
      Copying control file to `/usr/share/postgresql/13/extension/timescaledb_toolkit.control`
      [error] failed copying `timescaledb_toolkit.control` to `/usr/share/postgresql/13/extension/timescaledb_toolkit.control`: Permission denied (os error 13)
```
Manually copying timescaledb_toolkit.control into /usr/share/postgresql/13/extension/ folder didn't work. I had the following error when trying to create extension in Postgresql
```
CREATE EXTENSION timescaledb_toolkit;
ERROR:  extension "timescaledb_toolkit" has no installation script nor update path for version "1.4"
```
When I tried run all the installation steps as root, as suggested by another thread, then I had different error messages.
```
root@HP-Pavilion:~# cargo install --git https://github.com/JLockerman/pgx.git --branch timescale2 cargo-pgx && \
> cargo pgx init --pg13 pg_config
    Updating git repository `https://github.com/JLockerman/pgx.git`
     Ignored package `cargo-pgx v0.1.21 (https://github.com/JLockerman/pgx.git?branch=timescale2#e5b38342)` is already installed, use --force to override
   Validating pg_config
 Initializing data directory at /root/.pgx/data-13
      [error] problem running initdb: "/usr/lib/postgresql/13/bin/initdb" "-D" "/root/.pgx/data-13"
initdb: error: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
```
**To Reproduce**

**Expected behavior**
A clear and concise description of what you _expected_ to happen.

**Actual behavior**
A clear and concise description of what _actually_ happened.

**Screenshots**

**Additional context**
I am brand new to Rust/Cargo related stuff, please forgive me if I missed something obvious.

**Comment by marsdevapps** [comment]
Did you ever get this working?

**Comment by zhiyong80** [comment]
@marsdevapps no, I spent a few hours on it then gave up. I was hoping to try the timeweighted average  feature, but ended up writing my own code on the application side.

**Comment by k-bx** [comment]
Make `/usr/share/postgresql/13/extension/` whiteable by a non-root user, e.g. `chmod -R youruser:yourgroup /usr/share/postgresql/13/extension/`

**Comment by zhiyong80** [comment]
@k-bx after make both /usr/share/postgresql/13/extension and another folder that popped up error writeable, I was able to complete the installation. Too bad I didn't think of this. Thanks.
