### ISSUE TITLE
Unable to install on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by marsdevapps** [timescale/timescaledb-toolkit#297]
- OS: Ubuntu 20.04.3 LTS
 - PostgreSQL version 14
 - TimescaleDB Toolkit version 0.3.0
 - Installation method: source

Install fails on last step "cargo pgx install --release && \
cargo run --manifest-path ../tools/post-install/Cargo.toml -- pg_config"

15 errors, all related to not finding unit struct, variant, or constant in 'pg_sys'. 

First error:  error[E0425]: cannot find value `MAXDATELEN` in crate `pg_sys`

I'm following the instructions found at https://docs.timescale.com/timescaledb/latest/how-to-guides/hyperfunctions/install-toolkit/#installing-toolkit-on-self-hosted-timescaledb

**Comment by thaerlabs** [comment]
Same error here running same OS and PG Version

```
error[E0425]: cannot find value `MAXDATELEN` in crate `pg_sys`
  --> extension/src/serialization.rs:16:57
   |
16 |     dt: pg_sys::TimestampTz, buf: &mut [c_char; pg_sys::MAXDATELEN as _]
   |                                                         ^^^^^^^^^^ help: a constant with a similar name exists: `MAXINT8LEN`
```

**Comment by marsdevapps** [comment]
Just wondering if anyone has installed on PostgreSQL 14 and Ubuntu 20 successfully....

**Comment by marsdevapps** [comment]
Built and installed fine this morning with the latest sources.  I had the same "permission issues" as another user mentioned, but those were easily fixed/correct.  

Closing this.

**Comment by davidkohn88** [comment]
I think that the problem was that we hadn't yet added support for PG14, we did recently, so I'm glad it's working now!

**Comment by flixman** [comment]
@marsdevapps Excuse for reusing this close thread: I see that https://github.com/JLockerman/pgx.git, as indicated in the instructions, only supports up to pg13. How did you manage to install in pg14?  I see that pgx from zombodb, from which JLockerman's was forked, supports up to pg14 and I am trying it instead of the former, but... no idea if I am loosing my time here. Any advice?

**Comment by marsdevapps** [comment]
@flixman I don't remember the specifics now.  I know that I honestly just ended up following the instructions in the documentation and it installed fine.
