### ISSUE TITLE
Approximate COUNT DISTINCT

### ISSUE THREAD

**Issue by JLockerman** [timescale/timescaledb-toolkit#3]
## What's the functionality you would like to add ##
An approximate method to count the number of distinct elements in a table, such as HyperLogLog.

## How would the function be used ##
```SQL
SELECT approx_distinct(value) FROM data;
 approx_distinct
-----------------
              42

CREATE MATERIALIZED VIEW distinct_per_hour
WITH (timescaledb.continuous) AS
SELECT time_bucket(INTERVAL '1 hour', time) AS bucket,
    approx_distinct(value),
FROM data
GROUP BY bucket;

SELECT * FROM distinct_per_hour LIMIT 4;
         bucket         | approx_distinct 
------------------------+-----------------
   2020-01-03 01:00:00  |              31
   2020-01-03 02:00:00  |              27
   2020-01-03 03:00:00  |              30
   2020-01-03 04:00:00  |               1

```

## Why should this feature be added? ##
1. Without proper indexes `COUNT DISTINCT` can take time and space proportionate to the amount of memory, approximate counting can be done in ~constant space.
2. An approximate `COUNT DISTINCT` can be used with continuous aggregates to provide fast approximate counts for time intervals

## Remaining Work ##

- [x] Merge HyperLogLog++ implementation: https://github.com/timescale/timescale-analytics/pull/170
- [ ] Decide the final sizing API: https://github.com/timescale/timescale-analytics/issues/3#issuecomment-870662375
- [ ] Add Default collation to C collation transform (due to https://github.com/timescale/timescale-analytics/issues/148)

**Comment by JLockerman** [comment]
Am experimental version of this is available in [0.1.0](https://github.com/timescale/timescale-analytics/releases/tag/0.1.0), and should also be available on Forge soon.

**Comment by JLockerman** [comment]
Note: the hyperloglog impelemtation is in the process of being replaced with a Hyperloglog++ implementation on [the `jl/hllpp` branch](https://github.com/timescale/timescale-analytics/tree/jl/hllpp) (work is done on the actual implementation, it just needs to be attached to the SQL type).

**Comment by JLockerman** [comment]
Note from issue https://github.com/timescale/timescale-analytics/issues/148: all deterministic collations (which include all default collations) are treated the same for `text_hash()`, they are treated like binary hash. This means that we may want to default the default collation to always be equivalent to the C collation for HLL purposes, and avoid that entire class of errors. I don't think that will work for cases that care about ordering and not just equality though.

**Comment by JLockerman** [comment]
Open question: right now out `hyperloglog()` function takes in the number of registers as an argument, in other words the aggregate is `hyperloglog(num_registers, value)`. An alternative API would be to take the precision, so it would be `hyperloglog(precision, value)`. Which of these should be the final one? The former seems easier if you have a fixed space budget you want to stay within, while the other fits the Hyperloglog literature.

**Comment by JLockerman** [comment]
hyperloglog error table based on the hyperloglog relative standard error formula
```
1.04/sqrt(number_of_registers)
```

```
 precision ┃ registers ┃  error ┃  bytes
━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━╋━━━━━━━━
         4 ┃        16 ┃ 0.2600 ┃     12 
         5 ┃        32 ┃ 0.1838 ┃     24 
         6 ┃        64 ┃ 0.1300 ┃     48 
         7 ┃       128 ┃ 0.0919 ┃     96 
         8 ┃       256 ┃ 0.0650 ┃    192 
         9 ┃       512 ┃ 0.0460 ┃    384 
        10 ┃      1024 ┃ 0.0325 ┃    768 
        11 ┃      2048 ┃ 0.0230 ┃   1536 
        12 ┃      4096 ┃ 0.0163 ┃   3072 
        13 ┃      8192 ┃ 0.0115 ┃   6144 
        14 ┃     16384 ┃ 0.0081 ┃  12288 
        15 ┃     32768 ┃ 0.0057 ┃  24576 
        16 ┃     65536 ┃ 0.0041 ┃  49152 
        17 ┃    131072 ┃ 0.0029 ┃  98304 
        18 ┃    262144 ┃ 0.0020 ┃ 196608
```
We should add a function to output the error for a Hyperloglog, and possibly and aggregate function that takes in the error as a configuration parameter instead of size.

**Comment by jerryxwu** [comment]
With [hyperloglog](https://docs.timescale.com/api/latest/hyperfunctions/approx_count_distincts/hyperloglog/) out there for a while now, we received quite some feedback on users typically don't know how to set the number of buckets/registers. It would be ideal to have a version of the function that does not require the user to specify that.

@jfjoly @davidkohn88 It would be great if we could bump the priority of this feature.

**Comment by rtwalker** [comment]
Closed by #459

**Comment by prevostc** [comment]
I know it's closed, but I had to dig a bit more on hll until I find this table to decide on the bucket size: https://cloud.google.com/bigquery/docs/sketches#sketches_hll
Might be a good idea to have something similar in toolkit docs

**Comment by jerryxwu** [comment]
@prevostc thanks for the suggestion. we have a similar doc as well although not quite as polished as the one you pointed out. https://docs.timescale.com/api/latest/hyperfunctions/approximate-count-distinct/hyperloglog#approximate-relative-errors

**Comment by prevostc** [comment]
Thank you sir, yes I have seen this one but was missing the CI cols. Although it's just probably 1x, 2x and 3x error/sigma, it's nice to see it straight up. Seeing the col size in kb and mb also helped.
