### ISSUE TITLE
1.4.0 post-install fails due to no sql directory

### ISSUE THREAD

**Issue by grawlinson** [timescale/timescaledb-toolkit#303]
**Relevant system information:**
 - OS: Arch Linux
 - PostgreSQL version (output of `SELECT version();`): 13.4
 - TimescaleDB Toolkit version (output of `\dx timescaledb_toolkit` in `psql`): 1.4.0
 - Installation method: source

**Describe the bug**

The `sql` directory has been removed in-between `1.3.1` and `1.4.0`, so the extension cannot be installed.

**To Reproduce**
1. Download source tarball from GitHub
2. `cargo pgx init --pg13 pg_config`
3. `cd extension`
4. `cargo pgx package`
5. `cd ..`
6. `cargo run --manifest-path tools/post-install/Cargo.toml -- --dir "target/release/timescaledb_toolkit-pg13`

**Expected behavior**
Output from 1.3.1:

```
   Compiling timescaledb_toolkit v0.3.0 (/build/timescaledb-toolkit/src/timescaledb-toolkit-1.3.1/extension)
    Finished release [optimized + debuginfo] target(s) in 3m 50s

installing extension
      Copying control file to `target/release/timescaledb_toolkit-pg13/usr/share/postgresql/extension/timescaledb_toolkit.control`
      Copying shared library to `target/release/timescaledb_toolkit-pg13/usr/lib/postgresql/timescaledb_toolkit.so`
      Writing extension schema to `target/release/timescaledb_toolkit-pg13/usr/share/postgresql/extension/timescaledb_toolkit--1.3.1.sql`
     Finished installing timescaledb_toolkit
   Compiling xshell-macros v0.1.14
   Compiling same-file v1.0.6
   Compiling walkdir v2.3.1
   Compiling xshell v0.1.14
   Compiling post-install v0.1.0 (/build/timescaledb-toolkit/src/timescaledb-toolkit-1.3.1/tools/post-install)
    Finished dev [unoptimized + debuginfo] target(s) in 2.58s
     Running `target/debug/post-install --dir target/release/timescaledb_toolkit-pg13`
Generating Version 1.3.1
Upgradable From ["1.0", "1.1", "1.2", "1.3"]
```

**Actual behavior**

Output from 1.4.0:

```
   Compiling timescaledb_toolkit v0.3.0 (/build/timescaledb-toolkit/src/timescaledb-toolkit-1.4.0/extension)
warning: unused import: `pgx::*`
 --> extension/src/schema_test.rs:2:5
  |
2 | use pgx::*;
  |     ^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `timescaledb_toolkit` (lib) generated 1 warning
    Finished release [optimized + debuginfo] target(s) in 9m 28s

installing extension
      Copying control file to `target/release/timescaledb_toolkit-pg13/usr/share/postgresql/extension/timescaledb_toolkit.control`
      Copying shared library to `target/release/timescaledb_toolkit-pg13/usr/lib/postgresql/timescaledb_toolkit.so`
      [error] The path `./sql` does not exist.  Try running `cargo pgx schema` to fix this.
```

**Comment by tomjoro** [comment]
I had same problem. Then I noticed I was running postgres12 and had run this: `cargo install cargo-pgx && cargo pgx init --pg13 pg_config`. Change the pg13 to pg12 and run this and remaining steps.

**Comment by fl0cke** [comment]
I'm having the same problem here and i'm definitely using the correct postgres version. Here is the output of running `cargo pgx install --release`:

```
building extension with features `pg13`
"cargo" "build" "--release" "--features" "pg13" "--no-default-features"
   Compiling pgx-pg-sys v0.2.4
   Compiling pgx v0.2.4
   Compiling timescaledb_toolkit v0.3.0 (/home/forge/timescaledb-toolkit/extension)
    Finished release [optimized + debuginfo] target(s) in 11m 08s

installing extension
      Copying control file to `/usr/share/postgresql/13/extension/timescaledb_toolkit.control`
      Copying shared library to `/usr/lib/postgresql/13/lib/timescaledb_toolkit.so`
      [error] The path `./sql` does not exist.  Try running `cargo pgx schema` to fix this.
```

How can i fix this error? Running `cargo pgx schema` doesn't help unfortunately...

**Comment by tomjoro** [comment]
I also created that directory with "mkdir sql" and re-ran.  And then had to deal with the permissions problems on two files by chown the directories.

**Comment by fl0cke** [comment]
Oh wow, it was really just that simple... Thank you! They (timescale) should definitely document this somewhere or update the script to create this directory if it's not there.

**Comment by johnsxiong** [comment]
the same

**Comment by epgts** [comment]
We apologize for not responding sooner, but we suspect the major changes in pgx and toolkit since then obviate these problems.  Feel free to file a fresh bug report if problems persist.  Thanks for your interest in the Timescaledb toolkit!
