### ISSUE TITLE
Update mentions of Forge to be Cloud

### ISSUE THREAD

**Issue by clarkbw** [timescale/timescaledb-toolkit#305]
**Relevant system information:**
 - TimescaleDB Toolkit repo

**Describe the bug**
There are at least 5 instances within the README and code where the name Forge is used for the (now called) Timescale Cloud product (including this issue template).

https://github.com/timescale/timescaledb-toolkit/search?q=forge

**Comment by jerryxwu** [comment]
This has been resolved for a while now.
