### ISSUE TITLE
Ubuntu 20.04.3 LTS Build Failing due to snap daemon during pgx-pg-sys

### ISSUE THREAD

**Issue by MattForth** [timescale/timescaledb-toolkit#308]
**Relevant system information:**
 - OS: Ubuntu 20.04.3 LTS on an amazon ec2 micro (1 vCPU and 1GB of RAM)
 - PostgreSQL version 14
 - TimescaleDB Toolkit version 1.4 (I think, whatever the default currently is)
 - Installation method: Source

**Describe the bug**
I am attempting to build the toolkit from source on an amazon ec2 micro. I have tried following both the developer instructions and the instructions listed at: https://docs.timescale.com/timescaledb/latest/how-to-guides/hyperfunctions/install-toolkit/#install-timescaledb-toolkit. 

The central difference being the install of the fork of cargo-pgx from: _cargo install --git https://github.com/JLockerman/pgx.git --branch timescale2 cargo-pgx._ 

Following both I encounter an issue executing the final stage of the build:

cargo pgx install --release && \
cargo run --manifest-path ../tools/post-install/Cargo.toml -- pg_config

it builds all packages up to 345/348 (or 345/349 if the pgx fork is used) which is pgx-pg-sys. It then gets stuck there, I have let it run for hours, and have tried waiting for the instance to accumulate CPU credits so it can use full power for the duration of the build. 

Cargo doesn't produce an error, and the build doesn't 'fail' it just doesn't make any progress for hours at a time. 

Observing the system logs it appears soon after reaching the pgx-pg-sys package the daemon crashes and then spends the next hour or so trying to restart (it had attempted it 47 times) this time. I assume the same had occured during previous attempts but the logs don't go back that far. 

**To Reproduce**
I don't know what's causing the issue so not entriely sure how to reproduce? As far as I know it's an install on a standard ubuntu 20 ec2 micro. 

**Expected behavior**
Timescale toolkit build to complete as described in build from source instructions.

**Actual behavior**
The build gets stuck at 345/348 which is listed as pgx-pg-sys. This appears to be caused by the snap-daemon crashing during the build.

**Screenshots**
Dec  1 10:32:10 ip-172-31-17-218 dbus-daemon[430]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service' requested by ':1.46' (uid=0 pid=64364 comm="/usr/bin/gdbus call --system --dest org.freedeskto" label="unconfined")
Dec  1 10:32:10 ip-172-31-17-218 systemd[1]: Starting PackageKit Daemon...
Dec  1 10:32:10 ip-172-31-17-218 PackageKit: daemon start
Dec  1 10:32:10 ip-172-31-17-218 dbus-daemon[430]: [system] Successfully activated service 'org.freedesktop.PackageKit'
Dec  1 10:32:10 ip-172-31-17-218 systemd[1]: Started PackageKit Daemon.
Dec  1 10:37:34 ip-172-31-17-218 PackageKit: daemon quit
**Dec  1 10:41:12 ip-172-31-17-218 packagekitd[64367]: Error releasing name org.freedesktop.PackageKit: Timeout was reached** 
Dec  1 10:43:08 ip-172-31-17-218 CRON[64593]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Dec  1 10:44:59 ip-172-31-17-218 systemd[1]: snapd.service: Watchdog timeout (limit 5min)!
Dec  1 10:47:42 ip-172-31-17-218 snapd[445]: SIGABRT: abort
Dec  1 10:47:48 ip-172-31-17-218 systemd[1]: snapd.service: Killing process 445 (snapd) with signal SIGABRT.
Dec  1 10:47:49 ip-172-31-17-218 systemd[1]: packagekit.service: Succeeded.
Dec  1 10:47:49 ip-172-31-17-218 CRON[64603]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Dec  1 10:47:49 ip-172-31-17-218 snapd[445]: PC=0x55f9f87e32a1 m=0 sigcode=0
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: goroutine 0 [idle]:
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: runtime.futex(0x55f9fa135708, 0x80, 0x0, 0x0, 0x55f900000000, 0x7fff25fa0500, 0x55f9f87b6b75, 0xc0002079c8, 0x7fff25fa0520, 0x55f9f878c693, ...)
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/runtime/sys_linux_amd64.s:535 +0x21
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: runtime.futexsleep(0x55f9fa135708, 0x7fff00000000, 0xffffffffffffffff)
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/runtime/os_linux.go:44 +0x46
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: runtime.notesleep(0x55f9fa135708)
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/runtime/lock_futex.go:151 +0xa3
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: runtime.stoplockedm()
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/runtime/proc.go:2068 +0x8c
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: runtime.schedule()
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/runtime/proc.go:2469 +0x489
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: runtime.park_m(0xc000150c00)
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/runtime/proc.go:2610 +0xa3
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: runtime.mcall(0x0)
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/runtime/asm_amd64.s:318 +0x53
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: goroutine 1 [select, 1161 minutes]:
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: main.run(0xc00037ea20, 0x0, 0x0)
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/cmd/snapd/main.go:153 +0x4e5
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: main.main()
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/cmd/snapd/main.go:64 +0x10e
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: goroutine 6 [runnable]:
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: os/signal.signal_recv(0x0)
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/runtime/sigqueue.go:147 +0x9e
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: os/signal.loop()
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/os/signal/signal_unix.go:23 +0x24
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: created by os/signal.init.0
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/os/signal/signal_unix.go:29 +0x43
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: goroutine 27 [select, 16 minutes]:
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: github.com/snapcore/snapd/overlord/standby.(*StandbyOpinions).Start.func1(0xc000288550)
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/overlord/standby/standby.go:104 +0x12b
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: created by github.com/snapcore/snapd/overlord/standby.(*StandbyOpinions).Start
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/overlord/standby/standby.go:97 +0xaa
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: goroutine 28 [select, 16 minutes]:
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: github.com/snapcore/snapd/overlord.(*Overlord).Loop.func1(0x55f9f8786585, 0xc000462000)
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/overlord/overlord.go:444 +0x17a
Dec  1 10:47:50 ip-172-31-17-218 snapd[445]: gopkg.in/tomb%2ev2.(*Tomb).run(0xc000288a50, 0xc0004a6500)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/vendor/gopkg.in/tomb.v2/tomb.go:163 +0x2d
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: created by gopkg.in/tomb%2ev2.(*Tomb).Go
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/vendor/gopkg.in/tomb.v2/tomb.go:159 +0xc9
Dec  1 10:47:51 ip-172-31-17-218 systemd[1]: snapd.service: State 'stop-watchdog' timed out. Terminating.
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: goroutine 29 [IO wait, 1161 minutes]:
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: internal/poll.runtime_pollWait(0x7fa8fc135f08, 0x72, 0x0)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/runtime/netpoll.go:184 +0x57
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: internal/poll.(*pollDesc).wait(0xc000395298, 0x72, 0x0, 0x0, 0x55f9f917e359)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/internal/poll/fd_poll_runtime.go:87 +0x47
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: internal/poll.(*pollDesc).waitRead(...)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/internal/poll/fd_poll_runtime.go:92
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: internal/poll.(*FD).Accept(0xc000395280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/internal/poll/fd_unix.go:384 +0x1fa
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: net.(*netFD).accept(0xc000395280, 0x203000, 0xc000061cb0, 0x55f9f87b0403)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/net/fd_unix.go:238 +0x44
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: net.(*UnixListener).accept(0xc0004346c0, 0x55f9f9a17fe8, 0xc000061ce8, 0xc000061cc0)
ec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/net/unixsock.go:260 +0x49
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: github.com/snapcore/snapd/daemon.(*ucrednetListener).Accept(0xc000434720, 0xc000061da8, 0x18, 0xc000150a80, 0x55f9f8a78c86)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/daemon/ucrednet.go:112 +0x4a
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: net/http.(*Server).Serve(0xc0001020e0, 0x55f9f9a4f880, 0xc000434720, 0x0, 0x0)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/net/http/server.go:2896 +0x282
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: github.com/snapcore/snapd/daemon.(*Daemon).Start.func1(0x0, 0x0)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/daemon/daemon.go:373 +0x56
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: gopkg.in/tomb%2ev2.(*Tomb).run(0xc000102f30, 0xc0002d19c0)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/vendor/gopkg.in/tomb.v2/tomb.go:163 +0x2d
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: created by gopkg.in/tomb%2ev2.(*Tomb).Go
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/vendor/gopkg.in/tomb.v2/tomb.go:159 +0xc9
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: goroutine 30 [IO wait, 1161 minutes]:
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: internal/poll.runtime_pollWait(0x7fa8fc135e38, 0x72, 0x0)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/runtime/netpoll.go:184 +0x57
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: internal/poll.(*pollDesc).wait(0xc000395398, 0x72, 0x0, 0x0, 0x55f9f917e359)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/internal/poll/fd_poll_runtime.go:87 +0x47
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: internal/poll.(*pollDesc).waitRead(...)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/internal/poll/fd_poll_runtime.go:92
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: internal/poll.(*FD).Accept(0xc000395380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/internal/poll/fd_unix.go:384 +0x1fa
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: net.(*netFD).accept(0xc000395380, 0x203000, 0x0, 0x0)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/net/fd_unix.go:238 +0x44
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: net.(*UnixListener).accept(0xc0004346f0, 0xc000316780, 0x30, 0x30)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/net/unixsock_posix.go:162 +0x34
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: net.(*UnixListener).Accept(0xc0004346f0, 0xc000316780, 0x55f9f9a17fe8, 0xc00004d528, 0xc000207880)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/net/unixsock.go:260 +0x49
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: github.com/snapcore/snapd/daemon.(*ucrednetListener).Accept(0xc000434750, 0x55f9f99826c0, 0xc000316780, 0x55f9f98bc0c0, 0x55f9fa0d3dc0)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/daemon/ucrednet.go:112 +0x4a
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: net/http.(*Server).Serve(0xc0001020e0, 0x55f9f9a4f880, 0xc000434750, 0x0, 0x0)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/net/http/server.go:2896 +0x282
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: github.com/snapcore/snapd/daemon.(*Daemon).Start.func1.1(0x0, 0x0)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/daemon/daemon.go:365 +0x4b
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: gopkg.in/tomb%2ev2.(*Tomb).run(0xc000102f30, 0xc0002d19d0)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/vendor/gopkg.in/tomb.v2/tomb.go:163 +0x2d
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: created by gopkg.in/tomb%2ev2.(*Tomb).Go
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/vendor/gopkg.in/tomb.v2/tomb.go:159 +0xc9
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: goroutine 31 [select]:
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: main.runWatchdog.func1(0xc000288730, 0xc000102ee0)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/cmd/snapd/main.go:93 +0xe5
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: created by main.runWatchdog
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/cmd/snapd/main.go:91 +0x1e2
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: goroutine 56 [select, 1161 minutes]:
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: github.com/snapcore/snapd/overlord/ifacestate/udevmonitor.(*Monitor).Run.func1(0x1, 0xc00004d7a8)
c  1 10:47:51 ip-172-31-17-218 snapd[445]: github.com/snapcore/snapd/overlord/ifacestate/udevmonitor.(*Monitor).Run.func1(0x1, 0xc00004d7a8)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/overlord/ifacestate/udevmonitor/udevmon.go:147 +0x329
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: gopkg.in/tomb%2ev2.(*Tomb).run(0xc000352630, 0xc000644d00)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/vendor/gopkg.in/tomb.v2/tomb.go:163 +0x2d
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: created by gopkg.in/tomb%2ev2.(*Tomb).Go
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/vendor/gopkg.in/tomb.v2/tomb.go:159 +0xc9
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: goroutine 55 [syscall, 258 minutes]:
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: syscall.Syscall6(0x17, 0x6, 0xc0003cfe28, 0x0, 0x0, 0x0, 0x0, 0xc000490600, 0x200000003, 0xc000490600)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/syscall/asm_linux_amd64.s:44 +0x5
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: syscall.Select(0x6, 0xc0003cfe28, 0x0, 0x0, 0x0, 0x55f9f87b0403, 0x55f9f9a17500, 0xc0003cfe48)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/usr/lib/go-1.13/src/syscall/zsyscall_linux_amd64.go:1320 +0xa2
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: github.com/snapcore/snapd/osutil/udev/netlink.stopperSelectReadable(0x4, 0x5, 0x0, 0xc0004a8cc0, 0x19)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/osutil/udev/netlink/rawsockstop.go:57 +0x16c
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: github.com/snapcore/snapd/osutil/udev/netlink.RawSockStopper.func1(0xc0004d4880, 0xc000475168, 0x6)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/osutil/udev/netlink/rawsockstop.go:31 +0x4e
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: github.com/snapcore/snapd/osutil/udev/netlink.(*UEventConn).Monitor.func4(0xc0004d48a0, 0xc000314a80, 0xc000314ae0, 0xc000314b40, 0xc0001c6b00, 0x55f9f9a58100, 0xc0004d4880, 0xc000314a20)
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/osutil/udev/netlink/conn.go:139 +0x46
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: created by github.com/snapcore/snapd/osutil/udev/netlink.(*UEventConn).Monitor
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: #011/build/snapd/parts/snapd-deb/build/osutil/udev/netlink/conn.go:136 +0x247
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: rax    0xca
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: rbx    0x55f9fa1355c0
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: rcx    0x55f9f87e32a3
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: rdx    0x0
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: rdi    0x55f9fa135708
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: rsi    0x80
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: rbp    0x7fff25fa04e8
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: rsp    0x7fff25fa04a0
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: r8     0x0
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: r9     0x0
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: r10    0x0
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: r11    0x286
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: r12    0x0
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: r13    0x1
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: r14    0xc000315380
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: r15    0x55
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: rip    0x55f9f87e32a1
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: rflags 0x286
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: cs     0x33
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: fs     0x0
Dec  1 10:47:51 ip-172-31-17-218 snapd[445]: gs     0x0
Dec  1 10:47:51 ip-172-31-17-218 systemd[1]: snapd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec  1 10:47:51 ip-172-31-17-218 systemd[1]: snapd.service: Failed with result 'watchdog'.
Dec  1 10:47:51 ip-172-31-17-218 systemd[1]: snapd.service: Scheduled restart job, restart counter is at 1.
Dec  1 10:47:51 ip-172-31-17-218 systemd[1]: Stopped Snap Daemon.
Dec  1 10:47:51 ip-172-31-17-218 systemd[1]: Starting Snap Daemon...
Dec  1 10:47:53 ip-172-31-17-218 snapd[64608]: AppArmor status: apparmor is enabled and all features are available
Dec  1 10:55:16 ip-172-31-17-218 systemd[1]: snapd.service: start operation timed out. Terminating.
Dec  1 10:55:17 ip-172-31-17-218 systemd[1]: snapd.service: Failed with result 'timeout'.
Dec  1 10:55:19 ip-172-31-17-218 systemd[1]: Failed to start Snap Daemon.
Dec  1 10:55:20 ip-172-31-17-218 CRON[64631]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Dec  1 10:55:21 ip-172-31-17-218 systemd[1]: snapd.service: Scheduled restart job, restart counter is at 2.
Dec  1 10:55:27 ip-172-31-17-218 systemd[1]: Stopped Snap Daemon.
Dec  1 10:55:33 ip-172-31-17-218 systemd[1]: Starting Snap Daemon...
Dec  1 10:57:48 ip-172-31-17-218 systemd-networkd[385]: eth0: Could not set DHCPv4 address: Connection timed out
Dec  1 10:58:33 ip-172-31-17-218 systemd-networkd[385]: eth0: Failed
Dec  1 10:58:34 ip-172-31-17-218 systemd[1]: snapd.service: start operation timed out. Terminating.
Dec  1 10:58:35 ip-172-31-17-218 systemd[1]: snapd.service: Failed with result 'timeout'.
Dec  1 10:58:36 ip-172-31-17-218 systemd[1]: Failed to start Snap Daemon.
Dec  1 10:58:37 ip-172-31-17-218 systemd[1]: snapd.service: Scheduled restart job, restart counter is at 3.
Dec  1 10:58:39 ip-172-31-17-218 systemd[1]: Stopped Snap Daemon.
Dec  1 10:58:40 ip-172-31-17-218 systemd[1]: Starting Snap Daemon...

and it repeats as that from there trying to restart the Snap Daemon.

**Additional context**
It appears to be failure with org.freedesktop.PackageKit which then causes the snap daemon to crash but I don't know if this is a bug or a peculiarity of my build. As far as I know my instance is pretty standard and only has the standard version of ubuntu for an ec2 instance with postgresql 14 and timescale. I am also aware that 1GB of ram is very low for a build with cargo-pgx but I don't know if the logs indicate that that is the issue that is being encountered - if that is the case then I'm happy to upgrade to a chunkier ec2, but didn't want to without confirming that's the issue.

Sorry for the huge log dump but I don't know what is and isn't relevant from them. I am new to cargo and rust as I only got them for this particular build, so apologies if I've made a simple mistake and that's causing the failure. 

EDIT: Fixed formatting and grammar/spelling issues.

**Comment by vnadhan** [comment]
@MattForth I would be very happy to know on how you managed to resolve this. I face a similar issue in a `t3.micro` EC2 instance where the service PackageDaemon runs repeatedly and then there will be a network error in the logs that says the below 

``` 
ens5: Could not set DHCPv4 address: Connection timed out
```

I could also see from the EC2 monitoring statistics that the CPU credits usage were quite high the same time the EC2 failed.
