### ISSUE TITLE
Match timescaledb release package platforms/distributions

### ISSUE THREAD

**Issue by phemmer** [timescale/timescaledb-toolkit#322]
**Is your feature request related to a problem? Please describe.**
Currently the timescaledb-toolkit only releases packages for el/7, el/8, debian/bullseye, and ubuntu/hirsute. However TimescaleDB itself releases packages for these same distributions, as well as debian/buster, debian/stretch, ubuntu/bionic, ubuntu/focal, & ubuntu/impish. This means that any users who install TimescaleDB for one of these additional distributions won't be able to install timescaledb-toolkit from the repo, and instead will have to compile and distribute it manually.

**Describe the solution you'd like**
The packaging for timescaledb-toolkit should include all the same platforms/distributions that TimescaleDB itself is released for.

**Describe alternatives you've considered**
Build and deploy manually.

**Additional context**
timescaledb-toolkit packages: https://packagecloud.io/app/timescale/timescaledb/search?q=toolkit-postgresql-14&filter=all&filter=all&dist=  
timescaledb packages: https://packagecloud.io/app/timescale/timescaledb/search?q=+timescaledb-2-postgresql-14&filter=all&filter=all&dist=

**Comment by Xima** [comment]
+1 Specially for bionic with is still a commonly used LTS version

**Comment by jerryxwu** [comment]
@Xima we've just added bionic packages in the latest 1.11.0 release. Check them out.

**Comment by jerryxwu** [comment]
Toolkit 1.11.0 now have packages built for Debian/{buster, bulleye}, Ubuntu/{bionic, focal, jammy} on amd64. TimescaleDB and Toolkit are now in sync in terms of amd64 based platforms.
