### ISSUE TITLE
Consider enforcing rustfmt

### ISSUE THREAD

**Issue by epgts** [timescale/timescaledb-toolkit#336]
This would be a test that asserts no output from `diff source-file <(rustfmt source-file)`, i.e. that all files have been formatted with `rustfmt`.

This is an inexpensive test and part of the value of using a source code formatter is a consistent reading experience, so we'll want to run this on every push so we can have clean formatting before anyone else reads a change.

**Comment by rtwalker** [comment]
+1 for something like this. could also set up a pre-commit hook

**Comment by rtwalker** [comment]
closed by https://github.com/timescale/timescaledb-toolkit/pull/537
