### ISSUE TITLE
Build failure on ubuntu

### ISSUE THREAD

**Issue by DanielFarinaSande** [timescale/timescaledb-toolkit#337]
**Relevant system information:**
 - OS: Ubuntu 20.04.3
 - PostgreSQL version 14
 - Followed: https://github.com/timescale/timescaledb-toolkit

**Describe the bug**
When running:
```
cargo pgx install --release && \
cargo run --manifest-path ../tools/post-install/Cargo.toml -- pg_config
```
![imagen](https://user-images.githubusercontent.com/76769695/151949081-687b1345-f38f-4bc5-be81-f1a296e19f35.png)

This error is being reproduced despite I've already switched to nightly compiler while at the same time, as far as I see, there's no option Z specified:

![imagen](https://user-images.githubusercontent.com/76769695/151949474-acc29be0-9e8c-4a2b-95df-702ee3f83c3a.png)

**Comment by JLockerman** [comment]
@DanielFarinaSande I've never seen that issue before; my best guess is that it's a `cargo-pgx` issue. What version of cargo-pgx do you have installed? (you can check with cargo pgx --version).

**Comment by DanielFarinaSande** [comment]
> @DanielFarinaSande I've never seen that issue before; my best guess is that it's a `cargo-pgx` issue. What version of cargo-pgx do you have installed? (you can check with `cargo pgx --version`).

![imagen](https://user-images.githubusercontent.com/76769695/156719874-3327fab8-d2fe-4262-b917-d51bdbf9326a.png)

**Comment by epgts** [comment]
We apologize for not responding sooner, but we suspect the major changes in pgx and toolkit since then obviate these problems.  Feel free to file a fresh bug report if problems persist.  Thanks for your interest in the Timescaledb toolkit!
