### ISSUE TITLE
Install TimescaleDB Toolkit failed !

### ISSUE THREAD

**Issue by johnsxiong** [timescale/timescaledb-toolkit#346]
**Relevant system information:**
 - OS:  Mac OS 12.2.1
 - PostgreSQL version (output of `SELECT version();`): 13.5

  ```
cargo pgx install --release && \
  cargo run --manifest-path ../tools/post-install/Cargo.toml -- pg_config
```

result:
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/37213061/154834661-0d5b9c41-36f8-479c-a7e9-cfdc63e1cf0d.png">

**Comment by JLockerman** [comment]
@johnsxiong what version of `cargo-pgx` do you have installed? (you can check with `cargo pgx --version`). IIRC usually this occurs if you have a `0.1` version of `cargo-pgx` and we require a `0.2` version. If that's the case `cargo install --version 0.2.4 cargo-pgx` should fix it.

**Comment by johnsxiong** [comment]
Another Error ocured !
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/37213061/157200997-d63ebe3f-1605-4591-bdab-ec442f7cef56.png">

**Comment by rtwalker** [comment]
Hi @johnsxiong I'd like to help figure this one out if you're still looking to install the toolkit!

First, we've just upgraded the version of pgx we're using to `0.4.5` which has made life on macOS easier for me (especially with an M1 Mac). Maybe you'll have the same luck if you `cargo install --version '=0.4.5' cargo-pgx` and re-try the install steps?

Also the latest image you shared suggests you're looking to install on a database running PostgreSQL 14 (instead of version 13, mentioned originally). Is that correct?

**Comment by johnsxiong** [comment]
Hi, there
```
   Compiling pgx-pg-sys v0.4.5
   Compiling pgx-macros v0.4.5
   Compiling statrs v0.15.0
error: failed to run custom build command for `pgx-pg-sys v0.4.5`

Caused by:
  process didn't exit successfully: `/Users/johnxiong/timescaledb-toolkit/target/release/build/pgx-pg-sys-88051da767743237/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=PGX_PG_SYS_GENERATE_BINDINGS_FOR_RELEASE
  cargo:rerun-if-changed=/Users/johnxiong/.pgx/config.toml
  cargo:rerun-if-changed=include/pg10.h
  cargo:rerun-if-changed=include/pg11.h
  cargo:rerun-if-changed=include/pg12.h
  cargo:rerun-if-changed=include/pg13.h
  cargo:rerun-if-changed=include/pg14.h
  cargo:rerun-if-changed=cshim/pgx-cshim.c
  cargo:rerun-if-changed=cshim/Makefile

  --- stderr
  manifest_dir=/Users/johnxiong/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.4.5
  shim_src=/Users/johnxiong/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.4.5/cshim
  shim_dst=/Users/johnxiong/timescaledb-toolkit/target/release/build/pgx-pg-sys-62cf44ffb303443a/out/cshim
  Generating bindings for pg14
  [[bindings_diff]] "rustfmt" "/Users/johnxiong/timescaledb-toolkit/target/release/build/pgx-pg-sys-62cf44ffb303443a/out/pg14.rs"
  Error: Unable to write bindings file for pg14 to `/Users/johnxiong/timescaledb-toolkit/target/release/build/pgx-pg-sys-62cf44ffb303443a/out/pg14.rs`

  Caused by:
     0: Failed to run `rustfmt`, is it installed?
     1: No such file or directory (os error 2)

  Location:
      /Users/johnxiong/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.4.5/build.rs:626:18
(base) ➜  extension git:(main) cargo pgx --version
cargo-pgx 0.4.5
(base) ➜  extension git:(main)
```
