### ISSUE TITLE
Cargo PGX Install not working

### ISSUE THREAD

**Issue by CryptusChrist** [timescale/timescaledb-toolkit#347]
**Relevant system information:**
 - UBUNTU 20.04, Postgres 14 , TImescaleDB from source

**To Reproduce**
cargo pgx install --release && \ cargo run --manifest-path ../tools/post-install/Cargo.toml -- pg_config
Error: 
   0: `pgx-0.2.4` shouldn't be used with `cargo-pgx-0.3.3`, please use `pgx = "~0.3.3"` in your `Cargo.toml`.

Tried uninstalling and re-installing several times and keep getting this error message

**Comment by CryptusChrist** [comment]
This is what I am getting now::

'error: failed to run custom build command for `pgx-pg-sys v0.2.4`

Caused by:
  process didn't exit successfully: `/home/john/timescaledb-toolkit/target/release/build/pgx-pg-sys-074addf8b9d36800/build-script-build` (exit status: 1)
 `--- stdout
  cargo:rerun-if-env-changed=PGX_PG_SYS_SKIP_BINDING_REWRITE`

`  --- stderr
  manifest_dir=/root/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.2.4
  shim_src=/root/.cargo/registry/src/github.com-1ecc6299db9ec823/pgx-pg-sys-0.2.4/cshim
  shim_dst=/home/john/timescaledb-toolkit/target/release/build/pgx-pg-sys-40a9cbd99021ecc3/out/cshim`
  Error: Custom { kind: NotFound, error: "/root/.pgx/config.toml not found.  Have you run cargo pgx init` yet?" }
warning: build failed, waiting for other jobs to finish...
error: build failed
      [error] failed to build extension
``'

**Comment by epgts** [comment]
Hmm...  that says /root/.pgx/config.toml is missing.  Do you mean 
to run as root?  Have you run cargo pgx init as another user, or 
possibly missed it entirely?

**Comment by CryptusChrist** [comment]
Sorry thanks for your help.  It was something else with permissions I fixed it.
