### ISSUE TITLE
Using deprecated functionality in Rust 1.59.0

### ISSUE THREAD

**Issue by jerryxwu** [timescale/timescaledb-toolkit#353]
Got two warnings about the same deprecated functionality when building the kit with Rust 1.59.0

***1. flat_serialize/src/lib.rs***
```
flat_serialize (rust 1.59.0, note that switch back to 1.57.0 makes this warning disappear)
   Compiling flat_serialize v0.1.0 (/home/jerryw/timescaledb-toolkit/crates/flat_serialize/flat_serialize)
warning: use of deprecated associated function `std::array::IntoIter::<T, N>::new`: use `IntoIterator::into_iter` instead
   --> crates/flat_serialize/flat_serialize/src/lib.rs:187:33
	|
187 |     	for (i, t) in IntoIter::new(self).map(|s| s.into_owned()).enumerate() {
	|                             	^^^
	|
	= note: `#[warn(deprecated)]` on by default

warning: `flat_serialize` (lib) generated 1 warning
```

***2. lambda/parser.rs***
```
pipeline/lambda/parser.rs (rust 1.59.0, note that switch back to 1.57.0 makes this warning disappear)
   Compiling timescaledb_toolkit v0.3.0 (/home/jerryw/timescaledb-toolkit/extension)
warning: use of deprecated associated function `std::array::IntoIter::<T, N>::new`: use `IntoIterator::into_iter` instead
   --> extension/src/time_series/pipeline/lambda/parser.rs:406:27
	|
406 | 	std::array::IntoIter::new([
	|                       	^^^
	|
	= note: `#[warn(deprecated)]` on by default

warning: `timescaledb_toolkit` (lib) generated 1 warning
```

**Platform**: Ubuntu 20.04 running within WSL

**Comment by epgts** [comment]
It would be good of us to try to stay on top of these, but we should also be careful that we don't blindly update things and end up requiring newer Rust than we really need to.

Which means we need to figure out a definition of "newest Rust we require". How far back do we want to support? One definition might be "latest stable Red Hat". That's just a straw man. We might decide that we'd rather folks on systems as conservative as RHEL just install their own Rust first.

We ought to involve other Timescale teams publishing Rust code in this discussion.
