### ISSUE TITLE
Specialize freq_agg and topn_agg for bigints and text rather than supporting AnyElement

### ISSUE THREAD

**Issue by WireBaron** [timescale/timescaledb-toolkit#376]
Postgres functions that return values of type `AnyElement` are inherently ugly due to the requirement that the user provide a value exactly matching the return type as an input to the function.  This makes for an ugly and unpleasant user experience.  The goal of supporting `AnyElement` in these aggregates was to free the user from having to worry about the type, and it very much failed in this as now the user has to be exactly aware of the type in every instance where they want to get a value out of the aggregate.

A friendlier alternative would be implementations that support (at least implicit casts from) the types we expect or see customers using.  Ints and strings seem the most like values and should be our first priorities.  It may be worth having an AnyElement specialization available as a fallback for users who absolutely need it, but it should probably get its own unique name (`freq_agg_generic`?) to ensure no one accidentally uses it.

**Comment by JLockerman** [comment]
The specific issue is that the return type has to specified as an output. This means that if you have an aggregate storing some type `Foo`, to return a set of elements like `topn()` wants to do the call would have to look something like
```SQL
topn(agg, NULL::Foo)
```
while if the aggregate is specialized to a type, such as `TEXT, the call can look something like
```SQL
topn(agg)
```

**Comment by JLockerman** [comment]
I've been wondering if we could improve this with a marker function `type()` so that a generic call would look like
```SQL
topn(agg, type()::Foo)
```
which explains better what the second argument is for. (I _think_ the `type()` function can be `() -> TEXT` that always returns `NULL`)
