### ISSUE TITLE
TopN Aggregate Sketches

### ISSUE THREAD

**Issue by davidkohn88** [timescale/timescaledb-toolkit#38]
In situations where one has zipfian or other long tail distributions of items, one often wants an aggregate that computes the topN most frequent values and lops off the rest for storage and lookup efficiency reasons. Take the case where you're monitoring traffic by URL and want to show the top 100 URLs by traffic in a day, there might be millions of URLs that are hit, but most of them only have a few hits and what you care about are the top 100. An aggregate that stored the top 100 urls and their counts on a daily basis and then you could re aggregate across multiple days if needed (though it would be an approximation of the true top100, it would be relatively accurate). I think this could be significantly more useful than the count min sketch in #6 .

**Comment by davidkohn88** [comment]
Discussion in #40

**Comment by JLockerman** [comment]
We've heard rumors that this is a very popular feature.

**Comment by JLockerman** [comment]
https://github.com/timescale/timescaledb-toolkit/issues/6 should serve as a stepping stone to this

**Comment by WireBaron** [comment]
We're looking at providing this functionality using our frequency aggregate functionality.  Details in #365

**Comment by jfjoly** [comment]
Can we close this issue since this is completed : https://github.com/timescale/timescaledb-toolkit/issues/365 ?
