### ISSUE TITLE
Reduce the size of the toolkit extension

### ISSUE THREAD

**Issue by WireBaron** [timescale/timescaledb-toolkit#381]
Right now the toolkit code is unreasonably large.  We should at least strip symbols from our release builds and perhaps see if there is other low hanging fruit.  

This repo has further suggestions for reducing build size: https://github.com/johnthagen/min-sized-rust#optimize-for-size

**Comment by epgts** [comment]
@JLockerman found https://doc.rust-lang.org/cargo/reference/profiles.html#split-debuginfo which ought to be helpful.

**Comment by epgts** [comment]
Although we should certainly do issue #387 before digging into this.

**Comment by epgts** [comment]
My old trick for finding the largest code:

`nm -CSlr --size-sort .o/extension/release/libtimescaledb_toolkit.so | perl -lne '/^\S+\s+(\S+)\s+[tT]\s+(.*)/ || next; printf("\%5d $2\n", hex($1))'`

**Comment by epgts** [comment]
It seems pretty clear now that any code bloat problems we may have are
dwarfed by the size of debug info.

While improving our packaging scripts for Ubuntu, I noticed we were not
taking advantage of `dh_strip`'s automatic move of debug info into
separate packages.  With this fixed, we slim down from 99MB to 19MB,
with 14.6MB of that going into a separate, optional debug package,
allowing installations as small as 4.2MB:

```
101264	release/timescaledb_toolkit-pg14/usr/lib/postgresql/14/lib/timescaledb_toolkit.so
4340	/usr/lib/postgresql/14/lib/timescaledb_toolkit.so
14928	/usr/lib/debug/.build-id/1f/afd597118d54a5361151bb81c84bd7c66ce79e.debug
```

I haven't looked to see if our RPMs are also benefitting from any
packaging automation.  If they're not, and if we're unable to make that
happen, then we can apply the same technique `dh_strip` applies:

```sh
  # 1. Copy and compress debug info from SOFILE to DBGFILE.
  objcopy --only-keep-debug --compress-debug-sections SOFILE DBGFILE
  # 2. Aggressively strip SOFILE.
  strip --remove-section=.comment --remove-section=.note --strip-unneeded SOFILE
  # 3. Add reference to DBGFILE to SOFILE.  This doesn't save the path to
  #    DBGFILE; instead gdb looks for it in particular places (including the
  #    same directory gdb finds SOFILE in).
  objcopy --add-gnu-debuglink DBGFILE SOFILE
```

**Comment by epgts** [comment]
The RPM ships a 99MB binary.

**Comment by jfjoly** [comment]
Could we do a PR to https://github.com/timescale/timescaledb-docker-ha to 
Ideally use the package of toolkit or,
Otherwise use the same build config to reduce the size?
