### ISSUE TITLE
Create arm64 packages in the repository

### ISSUE THREAD

**Issue by wtfuzz** [timescale/timescaledb-toolkit#382]
**Is your feature request related to a problem? Please describe.**
I'm using Timescale on `aarch64` AWS EC2 nodes, and the official repository only has `x86_64`  binary packages.

**Describe the solution you'd like**
It would be convenient to be able to install a binary package of TimescaleDB toolkit on ARM architectures.

**Describe alternatives you've considered**
Building the toolkit from source on the target architecture as a workaround

**Comment by jerryxwu** [comment]
@wtfuzz thank you for the request. ARM64 support is something that we are looking closely at. I have couple questions for you. 
1. What Linux distro(s) are you using specifically? 
2. What kind(s) of binary packages are most interesting/useful to you?

**Comment by wtfuzz** [comment]
> * What Linux distro(s) are you using specifically?

On our ARM platforms, I use:

* Debian Bullseye
* Ubuntu 20.04 LTS

> * What kind(s) of binary packages are most interesting/useful to you?

* .deb package of `timescaledb-toolkit-postgresql-14` for the `arm64` architecture

**Comment by jfjoly** [comment]
@wtfuzz would a docker image for arm64 work for you?

**Comment by epgts** [comment]
see also #212

**Comment by jerryxwu** [comment]
@wtfuzz we've just released arm64 deb packages for Ubuntu (20.04 & 22.04) and Debian (10 & 11). Check them out. We'd love to hear any feedback you may have.
