### ISSUE TITLE
percentile_agg throws "returned Datum was NULL" error since version 2.5.1

### ISSUE THREAD

**Issue by idoberko2** [timescale/timescaledb-toolkit#383]
**Relevant system information:**
 - PostgreSQL version: `13.5`
 - TimescaleDB Toolkit version: `1.4`
 - Installation method: docker image - `timescale/timescaledb-ha:pg13.5-ts2.5.1-p4`

**Describe the bug**
Applying `percentile_agg()` on a column that contains `NULL` values occasionally throws:
```
ERROR: returned Datum was NULL
  Where: extension/src/uddsketch.rs:60:1
```

**To Reproduce**
1. Create a hypertable with a numeric column, in my case `feature_num_val`
2. Insert a couple of rows to the table, one with `feature_num_val` containing a value and another row with `NULL`
3. Run a query for a simple `percentile_agg()`:
```sql
SELECT timestamp, percentile_agg(feature_num_val)
FROM feature_values
GROUP BY timestamp;
```

**Expected behavior**
Query runs successfully, `percentile_agg` has a value.

**Actual behavior**
Query occasionally fails with:
```
Query 1 ERROR: ERROR:  returned Datum was NULL
CONTEXT:  extension/src/uddsketch.rs:60:1
```
By occasionally I mean about 50% of times. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6158608/162177188-8e5907cb-4702-4ec2-adc7-a48fcb65a174.png)
![image](https://user-images.githubusercontent.com/6158608/162177248-b711100e-5ff8-4287-9c83-4206b58b7fe2.png)

**Additional context**
Tested the same using `timescale/timescaledb-ha:pg13.4-ts2.5.0-p0` image, and the problem doesn't exist.

Tested the same using the latest `timescale/timescaledb-ha:pg13.6-ts2.6.0-latest` and the problem is still there.

**Comment by jerryxwu** [comment]
@idoberko2 thank you for reporting the issue with the details. We believe it's the same issue as #362. The fix for it will be included in the upcoming release. Stay tuned.
