### ISSUE TITLE
Refactor and simplify TimeVector

### ISSUE THREAD

**Issue by WireBaron** [timescale/timescaledb-toolkit#384]
Right now the time vector object is in a complex state where it's has many half realized ideas and premature optimizations baked into it.  It should be possible to reduce it to a much simpler object which is easier to develop around and move toward stability.

The following are some suggested subtasks for this:

- [ ] Refactor time-series crate (hopefully remove)
  - [ ] Remove any timevector objects here, they're superseded by the objects in timeseries.md
  - [ ] move gapfill objects and code needed by asap into asap.md (under extension/src)
  - [ ] if it's worth keeping the crate just for the remaining tspoint struct, rename it at least, but try to find a more elegant solution
- [ ] Rename any timeseries vestiges in comments or filenames to timevector
- [ ] Remove the enum variants of the Timevector object, leave just the explicit format with a flag to indicate sorted (we may want to add the enum back to handler another representation in the future, but this can be easily handled with our versioning and isn't worth carrying the complexity until then)

**Comment by jfjoly** [comment]
Related to [this PR](https://github.com/timescale/timescaledb-toolkit/pull/404#)
