### ISSUE TITLE
Changing bounds when doing counter_agg

### ISSUE THREAD

**Issue by xorduna** [timescale/timescaledb-toolkit#402]
Hi!

First of all, let me congratulate all of you for such an amazing product. Timescale really makes a difference when working with timeseries.

I am opening an issue because I found a problem when using delta and extrapolated_delta functions from counter_agg. From my point of view, there are problems with its accuracy.

I have a table with this kind of data:

| device_id| time | operating_hours | ph_con_tot |
|----------|-----|-------------------|-----------|
|9d5eaae0-421b-11ec-9949-7f0fdad2c99c|2021-11-01 00:02:01|438|76431585|
|9d5eaae0-421b-11ec-9949-7f0fdad2c99c|2021-11-01 00:17:01|438|76455826|
|9d5eaae0-421b-11ec-9949-7f0fdad2c99c|2021-11-01 00:32:01|438|76480251|
|9d5eaae0-421b-11ec-9949-7f0fdad2c99c|2021-11-01 00:47:01|438|76504595|
|9d5eaae0-421b-11ec-9949-7f0fdad2c99c|2021-11-01 01:02:01|439|76529217|
|9d5eaae0-421b-11ec-9949-7f0fdad2c99c|2021-11-01 01:17:01|439|76553266|
|9d5eaae0-421b-11ec-9949-7f0fdad2c99c|2021-11-01 01:32:01|439|76577539|
|9d5eaae0-421b-11ec-9949-7f0fdad2c99c|2021-11-01 01:47:01|439|76602789|

As you can see, that is counter data with an interval of 15 minutes which are set to the "clock" (0, 15, 30, 45).

When i try to calculate the daily deltas of operating_hours and ph_con_tot I use this query (I also calculate the extrapolated_delta).

```sql
    SELECT
      bucket,
      delta(summary) as delta_ph_con_tot,
      extrapolated_delta(
       with_bounds(
          summary,
          toolkit_experimental.time_bucket_range('1 day'::interval, bucket)
        ), 'prometheus'
       ) as extrapolated_delta_ph_con_tot,
      extrapolated_delta(
       with_bounds(
          summary,
          toolkit_experimental.time_bucket_range('1 day'::interval, bucket)
        ), 'prometheus'
       ) - delta(summary) as diff_delta_extrapolated,
       delta(summary_hours) as delta_operating_hours,
      extrapolated_delta(
       with_bounds(
          summary_hours,
          toolkit_experimental.time_bucket_range('1 day'::interval, bucket)
        ), 'prometheus'
       ) as extrapolated_delta_operating_hours,   
        min_time, max_time,
        max_time - min_time as interval
    FROM (
    SELECT time_bucket('1 day'::interval, time) AS bucket,
        counter_agg(time, ph_con_tot) as summary,
        counter_agg(time, operating_hours) as summary_hours,
        
        max(ph_con_tot) as max, min(ph_con_tot) as min, max(time) as max_time, min(time) as min_time
    FROM metrics_computer_wide
    where ph_con_tot is not null and device_id = '9d5eaae0-421b-11ec-9949-7f0fdad2c99c'
    GROUP BY time_bucket('1 day'::interval, time)) t
    ORDER BY bucket asc

```

And the result is:

|time|delta_ph_con_tot|extrapolated_delta_ph_con_tot|diff|delta_operating_hours|extrapolated_delta_operating_hours|min_time|max_time|interval|
|----|---|---|---|---|---|---|---|---|
|2021-11-01T00:00:00|2418078|2443531.424349965|25453.424349965062|23|23.242104994152047|2021-11-01T00:02:01|2021-11-01T23:47:01|23:45:00|
|2021-11-02T00:00:00|4873543|4924843.395631076|51300.39563107584|23|23.242104994152047|2021-11-02T00:02:01|2021-11-02T23:47:01|23:45:00|
|2021-11-03T00:00:00|5067154|5120492.403892935|53338.403892935254|23|23.242104994152047|2021-11-03T00:02:01|2021-11-03 23:47:01|23:45:00|
|2021-11-04 00:00:00|3468517|3502372.097555556|33855.09755555587|16|16.15617094017094|2021-11-04T00:02:01|2021-11-04T16:17:01|16:15:00|
|2021-11-05T00:00:00|408414|476483.00000000006|68069.00000000006|2|2.3333333333333335|2021-11-05 08:47:01|2021-11-05 10:17:01|01:30:00|
|2021-11-08T00:00:00|2739589|2797242.067631356|57653.06763135595|12|12.252533066666668|2021-11-08T11:21:43|2021-11-08 23:51:43|12:30:00|

As you can see, since delta uses min and max time to do the calculations, we only account for 23 hours per day, and this error is translated to the ph_con_tot (which obviously is much harder to guess).

I uploaded also fake data which is adjusted to the clock (0, 15, 30, 45)

| device_id| time | operating_hours | ph_con_tot |
|----------|-----|-------------------|-----------|
|82b430a1-27c4-4670-afb3-7af86d990fd3|2022-04-18 00:00:00|0|0|
|82b430a1-27c4-4670-afb3-7af86d990fd3|2022-04-18 00:15:00|0|29|
|82b430a1-27c4-4670-afb3-7af86d990fd3|2022-04-18 00:30:00|0|110|
|82b430a1-27c4-4670-afb3-7af86d990fd3|2022-04-18 00:45:00|0|207|
|82b430a1-27c4-4670-afb3-7af86d990fd3|2022-04-18 01:00:00|1|288|
|82b430a1-27c4-4670-afb3-7af86d990fd3|2022-04-18 01:15:00|1|361|
|82b430a1-27c4-4670-afb3-7af86d990fd3|2022-04-18 01:30:00|1|388|
|82b430a1-27c4-4670-afb3-7af86d990fd3|2022-04-18 01:45:00|1|406|
|82b430a1-27c4-4670-afb3-7af86d990fd3|2022-04-18 02:00:00|2|413|
|82b430a1-27c4-4670-afb3-7af86d990fd3|2022-04-18 02:15:00|2|420|
|82b430a1-27c4-4670-afb3-7af86d990fd3|2022-04-18 02:30:00|2|485|
|82b430a1-27c4-4670-afb3-7af86d990fd3|2022-04-18 02:45:00|2|488|
|82b430a1-27c4-4670-afb3-7af86d990fd3|2022-04-18 03:00:00|3|506|

And run the same query:

|time|delta_ph_con_tot|extrapolated_delta_ph_con_tot|diff|max|min|delta_operating_hours|extrapolated_delta_operating_hours|min_time|max_time|interval|
|----|---|---|---|---|---|---|---|---|---|---|
|2022-04-18T00:00:00|4611|4659.536788175438|48.53678817543823|4611|0|23|23.242104994152047|2022-04-18T00:00:00|2022-04-18T23:45:00|23:45:00!
|2022-04-19T00:00:00|4409|4455.410474748538|46.410474748538036|9052|4643|23|23.242104994152047|2022-04-19T00:00:00|2022-04-19T23:45:00|23:45:00|
|2022-04-20T00:00:00|5173|5227.452571076024|54.45257107602356|14261|9088|23|23.242104994152047|2022-04-20T00:00:00|2022-04-20T23:45:00|23:45:00|
|2022-04-21T00:00:00|4628|4676.715735345029|48.715735345029316|18938|14310|23|23.242104994152047|2022-04-21T00:00:00|2022-04-21T23:45:00||23:45:00
|2022-04-22T00:00:00|4860|4911.157837894737|51.157837894736986|23816|18956|23|23.242104994152047|2022-04-22T00:00:00|2022-04-22T23:45:00|23:45:00|
|2022-04-23T00:00:00|4752|4802.020997052631|50.020997052631174|28627|23875|23|23.242104994152047|2022-04-23T00:00:00|2022-04-23T23:45:00|23:45:00|
|2022-04-24T00:00:00|4676|4725.22099794152|49.22099794152018|33315|28639|23|23.242104994152047|2022-04-24 00:00:00|2022-04-24T23:45:00|23:45:00|
|2022-04-25T00:00:00|4072|4114.863110269006|42.86311026900603|37443|33371|23|23.242104994152047|2022-04-25 00:00:00|2022-04-25 23:45:00|23:45:00|
|2022-04-26T00:00:00|4245|4289.684160877193|44.68416087719288|41749|37504|23|23.242104994152047|2022-04-26T00:00:00|2022-04-26T23:45:00|23:45:00|
|2022-04-27T00:00:00|4713|4762.610471192982|49.610471192982004|46560|41847|23|23.242104994152047|2022-04-27T00:00:00|2022-04-27T23:45:00|23:45:00|

And here are my questions / doubts / concerns:

- As you can see, when data is not on the clock delta is calculated with max adn min, which is opionanted because even if we know there can be some error, its easy to calculate. And since we really know which percentage of the real counter (those are just samples) falls before or later the 0 minute, it seems fair that the operation is done.

- This is why I imagine extrapolated data has been created, but as you can see, it seems that extrapolated data adds round 1%, which for ph_con_tot does the job and reduces the difference, between real value and calculated value, but if you check with operating hours the error is still to big

- If we look at the data "on the clock", then there are no guesses, we know exactly which is the delta for a given period of time. But how counter_agg is impelmented, it misses the upper bound, which in this case has very valuable information.

- Would not it make sense to add the 00 minute to the bounds when calculating counter aggregates?

- Would it be possible to have another extrapolated delta that takes those bounds into account or does some more complex calculations?

- Is there any way to add extend the bounds in the query? 

- I would be more than happy to collaborate in this issue, but I never touched rust ... I have been exploring the code, but I am having problems finding where this exact implementation is placed.

- To add some context on why this is so important to us, we are metering energy, and some of our information is used to do some billing based on the kWh, this is why we need this calculation to be the most accurate. And I can understand that if the data is not "on the clock", there should be some error margin, but I don't think it makes sense if we can now exactly the delta.

BTW, I am opening an issue here, because I have been discussing this issue with Timescale support team and they asked me to do so.

Thank you very much in advance for reviewing this issue!

**Comment by JLockerman** [comment]
Hello,

> First of all, let me congratulate all of you for such an amazing product. Timescale really makes a difference when working with timeseries.


Thanks you for the kind words, we always like hearing about people using the database 😊.

If I understand correctly (and I could very easily have missed something!) you've seen 2  main issues:

1. The delta is being calculated over strange buckets, which causes error in the resulting value.
2. `extrapolated_delta()` is itself a bit of a strange operation, and the method we're using isn't always the best method by which to calculate it.

I _think_ these have separate causes, so I'm going to address each of them individually.

## 23 hour buckets ##

I think this might be an issue with how `time_bucket_range()` interacts with `counter_agg()`: `time_bucket_range()` uses a half-open interval, and I'm starting to suspect that `counter_agg()` needs a fully-closed interval to generate correct values. Would you try replacing the calls to
```
toolkit_experimental.time_bucket_range('1 day'::interval, bucket)
```
with calls to
```
tstzrange(time_bucket(bucket_width, ts), time_bucket(bucket_width, ts + bucket_width), '[]')
```
and see if it helps fix the problem?

## `extrapolated_delta()` algorithm ##

The code that we currently use for `extrapolated_delta()` can be found [here](https://github.com/timescale/timescaledb-toolkit/blob/e1375a932c4e5354bcada83fe6110ac91c6ce750/crates/counter-agg/src/lib.rs#L226-L277). As you've noticed, it's a opinionated and slightly finicky implementation. This is because else this particular implementation is designed to be compatible with Prometheus above all else, and that's what Prometheus does. We'd be happy to add other algorithms to extrapolate deltas, so as a first question: what do think is the best way to perform this calculation?

**Comment by xorduna** [comment]
Hi,

Yeah, you are right, you summarized my concerns very well :).

Regarding the issues:

**23 Hour buckets**

I tried to execute:

```sql
SELECT
	tstzrange(time_bucket('1 day'::interval, time), time_bucket('1 day'::interval, time + '1 day'::interval), '[]'),
	extrapolated_delta(
		with_bounds(
			counter_agg(time, operating_hours),
			tstzrange(time_bucket('1 day'::interval, time), time_bucket('1 day'::interval, time + '1 day'::interval), '[]')
		), 'prometheus'
	),
	delta(
		with_bounds(
			counter_agg(time, operating_hours),
			tstzrange(time_bucket('1 day'::interval, time), time_bucket('1 day'::interval, time + '1 day'::interval), '[]')
		)
	),
	min(operating_hours), max(operating_hours),
	min(time), max(time)
FROM metrics_wide
WHERE operating_hours is not null and device_id = '82b430a1-27c4-4670-afb3-7af86d000001'
GROUP BY tstzrange(time_bucket('1 day'::interval, time), time_bucket('1 day'::interval, time + '1 day'::interval), '[]')
ORDER BY tstzrange(time_bucket('1 day'::interval, time), time_bucket('1 day'::interval, time + '1 day'::interval), '[]') asc
```
But the result is the same. Maybe I am doing wrong, but the problem is with the `GROUP BY`. I cannot use your proposal in the select part, because it is not in the `GROUP BY` clause.

I see where you want to go, because you are creating like a fake range with the next day, but from my perspective the `GROUP BY` splits the rows, and row timestamped with `2022-02-03 00:00:00` falls in the previous or next bucket, but its value should fall in both.

AS I said, maybe I am doing it wrong because I am still a novice with Timescale. In any case, the extrapolated delta gave the same result: 23.24 avg.

**extrapolated_delta()**

I knew it was because of `prometheus` but that was one of the reasons because we decided to use Timescale directly instead of `promscale` as a query layer. In fact, Both InfluxDB and Victoria Metrics reduced the error in the deltas calculations. I didn't try with this sample data, and i will do it this week or the next one.

In any case, I would be more than happy to contribute in creating a new kind of delta. But I need to do some introduction here. Back in 2011 I was one of the founders and core engineers of DEXMA, a platform for energy management software. So we were dealing with timeseries at that moment and we created our own solution based in Java and MongoDB. Deltas were a big issue then. So, let me explain how we were calculating them, which IMHO, I think it is a reasonable way.

- First of all, we tried to get data "to the clock" to avoid extrapolations.
- When data was on the clock, we calculated delta taking into account the data from 00:01:00 to 00:02:00. We queried the data, made the calculations and persisted the data back to the database. What we are trying to do here is quite different, because we are calculating data in real time.
- We calculated deltas for 5m, 15m, 1h, 1d, 1w, 1m.
- In case there was no data for an specific time bucket (for example, data was every 15m) then we distributed the delta equally among the smaller buckets. For example, if we got 100 at 01:45:00 and 130 at 0
- 20:00:00, then we created a delta of 10 for each of the buckets at 01:45:00, 01:50:00, 01:55:00, 02:00:00.
- If there was no data for the whole day, then we created an equal delta for each hour.
- If data was not "on the clock", then we calculated the delta between the two datapoints (for example 100 at 00:01:23 and 140 at 00:01:38, then we splited that delta of 30, proportionally between the two buckets: 30 - 23 = 7, 30 - 38 = 8, 40 * (7/15) was added to the 01:30:00, and 40 * (8/15) was added to the 01:45:00.

As I said, that was done as a job in background, but it was pretty quick.

In any case, the main issue I see here, is that a "GROUP BY" makes the data points to fall in one or another bucket, but they need to be evaluated in both, because they contain data valuable to calculate deltas for both buckets.

What are your thoughts?

I atteched as a file the same sample data I am doing for those tests. data in device terminated with 0001 is on the clock, device 0002 is drifted 5 minutes.

[sample-data-timescale-deltas.txt](https://github.com/timescale/timescaledb-toolkit/files/8627415/sample-data-timescale-deltas.txt)

Thanks!

**Comment by WireBaron** [comment]
@xorduna

For the 23 Hour bucket problem we've realized this comes from our `with_bounds` function not having all the information it needs to figure out the boundaries of the interval.  We have an idea for a workaround for this, which we've detailed in #440 

Please take a look and let us know if this would be a workable solution for you.

**Comment by jfjoly** [comment]
@xorduna , were you able to check the proposal in #440 ? We would love your feedback 🙏

**Comment by xorduna** [comment]
Hi @WireBaron  and @jfjoly!

Sorry for the late reply!

Yes, I read issue #440 and even I am not an expert with window functions, to have the adjacent values will make a difference because everybody will be able to calculate its own version of the interpolated delta.

For example, if previous value is at 00:55 and next value is at 2:10, we will be able to get a very acurate calculation for the delta between 01:00 and 02:00.

**Comment by davidkohn88** [comment]
@xorduna I think we've solved this with the interpolating accessors with window functions, but feel free to reopen if we haven't addressed!
