### ISSUE TITLE
Error upgrading Timescale Toolkit

### ISSUE THREAD

**Issue by tbnobody** [timescale/timescaledb-toolkit#406]
**Relevant system information:**
 - OS: Debian 11.3
 - PostgreSQL version (output of `SELECT version();`): PostgreSQL 13.5 (Debian 13.5-0+deb11u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
 - TimescaleDB Toolkit version (output of `\dx timescaledb_toolkit` in `psql`): 1.5.2
 - Installation method: debian package

**Describe the bug**
If I try to update to the latest version using `apt upgrade` I get the following error message:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  timescaledb-toolkit-postgresql-13
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/18.2 MB of archives.
After this operation, 10.8 MB of additional disk space will be used.
Do you want to continue? [Y/n]
dpkg-deb: error: parsing file '/tmp/dpkg-deb.Wm8Y3B/control' near line 2 package 'timescaledb-toolkit-postgresql-13':
 'Version' field value 'forge-stable-1.6.0~debian11': version number does not start with digit
Traceback (most recent call last):
  File "/usr/share/apt-listchanges/DebianFiles.py", line 124, in readdeb
    output = subprocess.check_output(command)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dpkg-deb', '-f', '/var/cache/apt/archives/timescaledb-toolkit-postgresql-13_forge-stable-1.6.0~debian11_amd64.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/apt-listchanges", line 323, in <module>
    main(config)
  File "/usr/bin/apt-listchanges", line 104, in main
    pkg = DebianFiles.Package(deb)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 358, in __init__
    parser.readdeb(self.path)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 127, in readdeb
    raise RuntimeError(_("Error processing '%(what)s': %(errmsg)s") %
RuntimeError: Error processing '/var/cache/apt/archives/timescaledb-toolkit-postgresql-13_forge-stable-1.6.0~debian11_amd64.deb': Command '['dpkg-deb', '-f', '/var/cache/apt/archives/timescaledb-toolkit-postgresql-13_forge-stable-1.6.0~debian11_amd64.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.
dpkg: error processing archive /var/cache/apt/archives/timescaledb-toolkit-postgresql-13_forge-stable-1.6.0~debian11_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'timescaledb-toolkit-postgresql-13':
 'Version' field value 'forge-stable-1.6.0~debian11': version number does not start with digit
Errors were encountered while processing:
 /var/cache/apt/archives/timescaledb-toolkit-postgresql-13_forge-stable-1.6.0~debian11_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by jerryxwu** [comment]
@tbnobody thank you for reporting the issue. Have you tried [this deb package](https://packagecloud.io/timescale/timescaledb/packages/debian/bullseye/timescaledb-toolkit-postgresql-13_1.6.0~debian11_amd64.deb) that follows the toolkit's normal package naming convention?

**Comment by tbnobody** [comment]
Sorry for the late response. I did not specify any version. I previously just added the repo:
`deb https://packagecloud.io/timescale/timescaledb/debian/ bullseye main`
and installed one package:
apt install `timescaledb-toolkit-postgresql-13`

Now some time later, I got the above message during a regular update.

**Comment by rovaniemi** [comment]
@jerryxwu I got a similar error with ubuntu 20.04 when tried to upgrade 1.5.2 to 1.6.0

```bash
ubuntu:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  timescaledb-toolkit-postgresql-14
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 18.3 MB of archives.
After this operation, 10.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://packagecloud.io/timescale/timescaledb/ubuntu focal/main amd64 timescaledb-toolkit-postgresql-14 amd64 forge-stable-1.6.0~ubuntu20.04 [18.3 MB]
Fetched 18.3 MB in 1s (18.9 MB/s)
dpkg: error processing archive /var/cache/apt/archives/timescaledb-toolkit-postgresql-14_forge-stable-1.6.0~ubuntu20.04_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'timescaledb-toolkit-postgresql-14':
 'Version' field value 'forge-stable-1.6.0~ubuntu20.04': version number does not start with digit
Errors were encountered while processing:
 /var/cache/apt/archives/timescaledb-toolkit-postgresql-14_forge-stable-1.6.0~ubuntu20.04_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by rovaniemi** [comment]
> @jerryxwu I got a similar error with ubuntu 20.04 when I tried to upgrade toolkit from 1.5.2v to 1.6.0v
> 
> ```shell
> ubuntu:~$ sudo apt upgrade
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Calculating upgrade... Done
> The following packages will be upgraded:
>   timescaledb-toolkit-postgresql-14
> 1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Need to get 18.3 MB of archives.
> After this operation, 10.8 MB of additional disk space will be used.
> Do you want to continue? [Y/n] y
> Get:1 https://packagecloud.io/timescale/timescaledb/ubuntu focal/main amd64 timescaledb-toolkit-postgresql-14 amd64 forge-stable-1.6.0~ubuntu20.04 [18.3 MB]
> Fetched 18.3 MB in 1s (18.9 MB/s)
> dpkg: error processing archive /var/cache/apt/archives/timescaledb-toolkit-postgresql-14_forge-stable-1.6.0~ubuntu20.04_amd64.deb (--unpack):
>  parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'timescaledb-toolkit-postgresql-14':
>  'Version' field value 'forge-stable-1.6.0~ubuntu20.04': version number does not start with digit
> Errors were encountered while processing:
>  /var/cache/apt/archives/timescaledb-toolkit-postgresql-14_forge-stable-1.6.0~ubuntu20.04_amd64.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```

If someone faces this issue and is looking for a 'quick fix', here are the steps I took to fix this issue:


```
# Download the package without installing, which will place it in /var/cache/apt/archives/
sudo apt -d install  timescaledb-toolkit-postgresql-14

# Extract the package
dpkg-deb -R /var/cache/apt/archives/timescaledb-toolkit-postgresql-14_forge-stable-1.6.0~ubuntu20.04_amd64.deb ./timescale-toolkit-1.6.0

# Edit the /some/place/DEBIAN/control file so that the Version string does not start with an forge-stable 
nano ./timescale-toolkit-1.6.0

# change forge-stable-1.6.0~ubuntu20.04 to 1.6.0~ubuntu20.04 and then install it

dpkg-deb -b ./timescale-toolkit-1.6.0 timescale-toolkit-1.6.0.deb
dpkg -i timescale-toolkit-1.6.0.deb

```

**Comment by jerryxwu** [comment]
@rovaniemi @tbnobody thank you both for reporting the issue and a workaround! We've reproduced the case and it will be fixed in the coming version.

**Comment by tbnobody** [comment]
Works perfectly with version 1.7
