### ISSUE TITLE
Make toolkit dependency versions explicit

### ISSUE THREAD

**Issue by jerryxwu** [timescale/timescaledb-toolkit#415]
To stabilize our development env and have good confidence about what's working, we want to make versions of dependencies explicit:

- [x] Ubuntu #414 
- [ ] Rust
- [x] PGX tool #409 . Note that the crates that PGX depends on will be taken care of by `cargo update`.
- [x] PostgreSQL - we are already doing this.

Also,

- [x] Establish a cadence to update the list of dependencies regularly, including doing `cargo update` regularly as a pre-planning step.  (NOTE - `cargo update` does not update major versions, which is what we need to stay on top of)

**Comment by rtwalker** [comment]
Can we check the Ubuntu box now that the linked PR is merged?

To declare an explicit Rust version requirement, I guess we could add a [`rust-version` field ](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) in `extension/Cargo.toml`. Is there any need to do that for all of the other packages in the workspace?

**Comment by jerryxwu** [comment]
> Can we check the Ubuntu box now that the linked PR is merged?
Yes makes sense. Just checked.

**Comment by jerryxwu** [comment]
I consider this done now.
