### ISSUE TITLE
Build support for using window functions to avoid gaps caused by postgres grouping

### ISSUE THREAD

**Issue by WireBaron** [timescale/timescaledb-toolkit#440]
We have several aggregates that care more about the intervals between points than the actual points themselves.  Aggregates like `time_weight` and `state_agg` collect data based upon a pairwise consideration of the values at adjacent points and the time distance between them.

Unfortunately, these aggregates have a major weakness when data is grouped by time range, which is a very common use case.  When Postgres groups data, each point is uniquely assigned to one group, and a function called on that group has no visibility into adjacent groups.  This breaks our ability to do pairwise computations at the boundaries between groups.

We should be able to work around this using our pipeline functionality, but it will take a significant effort to design and mature a robust solution based around this (and this might not even be viable for mega-scale workloads).  Fortunately Postgres does have a mechanism for this problem that we can leverage for a more immediate workaround, and that is window functions.

The idea is that we can provide a function that will take the previous and next points of the data, as well as the time range that it is supposed to be covering after grouping, and adjust the aggregate to contain a correctly computed start and end point to completely cover its range.  Users can then use a window function to get the previous and next points when calling this function.  This is made a little easier the fact that these interval aware aggregates are necessarily already storing the first and last points of the range in order to support `rollup` behavior.

In practice, this is how this might look using a new `interpolated_average` (we may be able to come up with a better name) function on a time weight aggregate:

```SQL
SELECT
  bucket,
  interpolated_average(
    agg,  
    bucket,
    '1 day'::interval,
    lag(agg) OVER (ORDER BY bucket),
    lead(agg) OVER (ORDER BY bucket)
  )
FROM (
  SELECT
    time_bucket('1 day', time) bucket,
    time_weight('Linear', time, value) agg
  FROM tbl
  GROUP BY bucket
) s;
```

Related issues:
- #358
- #402
- #323

**Comment by JLockerman** [comment]
With accessor syntax
```sql
SELECT
  bucket,
  agg -> interpolated_average(
    bucket,
    '1 day'::interval,
    lag(agg) OVER (ORDER BY bucket),
    lead(agg) OVER (ORDER BY bucket)
  )
FROM (
  SELECT
    time_bucket('1 day', time) bucket,
    time_weight('Linear', time, value) agg
  FROM tbl
  GROUP BY bucket
) s;
```

**Comment by xorduna** [comment]
HI!

I think this can be a good option when dealing with those delta aggregates.

I just have one question, are you planning on a solution that requires the developer to work on the specific implementation of their aggregation?

I mean, lets take a case where boundary points for time rage 01:00 - 02:00 are at 0:55 and 02:10, some developers will preffer to consider delta as the difference between 01:10 and 02:10, but others might prefer to interpolate in the interval 0:55 - 01:10 and 01:55 - 2:10.

I mean what is important IMHO are the 4 values that are after and before the boundaries of the bucket.

**Comment by davidkohn88** [comment]
Hi @xorduna !

I think the general way that this will be handled is that the range will be provided by the size of the time bucket. So in the example above, this accessor would calculate it for the range from 01:00-02:00, and depending on the way the aggregate handles it, it would essentially interpolate to the edges of the bucket. So, in this case, we're looking at a `time_weight` function that does `Linear` interpolation, so we would linearly interpolate between the points at 0:55 & 1:10, and then find the point at the bucket edge (01:00). That would then be used for the delta calculation. If the `time_weight` function had been used with  `LOCF` interpolation, then the 0:55 value would just be carried forward, as called for in that method. 

Some of the other aggregates that this applies to are relatively clear, for instance, for `state_agg` it should use LOCF as that's always how that works. For `counter_agg`, I think we'd probably do `Linear`, but I'm not 100% sure that's right. Some of these might need a parameter that takes in the way we should do interpolation, if the underlying aggregate doesn't specify, but I think for most there will be a clear way. 

I'm not 100% sure if that's what you're asking, so please clarify if I've just spouted off on something that was completely different than what you meant!

**Comment by xorduna** [comment]
IMHO, I think `Linear` interpolation approach is the best for skewed data. This was what we were doing at DEXMA. In any case, if you want to run any cost/money related calculation on timeseries data you should ensure that the data is not skewed.
