### ISSUE TITLE
timescaledb-toolkit 1.7.0 has three open security advisories in it's dependency tree

### ISSUE THREAD

**Issue by jaskij** [timescale/timescaledb-toolkit#452]
**Relevant system information:**
None relevant

**Describe the bug**

[`cargo-deny`](https://embarkstudios.github.io/cargo-deny/) lists three security advisories:

- https://rustsec.org/advisories/RUSTSEC-2022-0013
- https://rustsec.org/advisories/RUSTSEC-2022-0006
- https://rustsec.org/advisories/RUSTSEC-2021-0124

and a further three warnings

- `serde_cbor` is unmaintained
- `crossbeam-utils` is using a yanked version
- ditto for `sha2`

**To Reproduce**

1. `cargo install cargo-deny`
2. clone the repository
3. check out 1.7.0
4. `cargo deny init` (will create `deny.toml` with default settings for `cargo-deny`)
5. `cargo deny check advisories` to list advisories and other security concerns

**Expected behavior**

The check should output a clean bill of health. For either `cargo-deny` or `cargo-audit`. If the toolkit is not impacted by a specific advisory, I would expect a configuration which would skip those checks, with an explanation (seems this options is only available for `cargo-deny`).

I would also expect for either of this tools to be run in your CI.

**Actual behavior**

The toolkit is *not* checked against RustSec Advisory Database *at all*.

**Comment by jaskij** [comment]
Checking further, https://rustsec.org/advisories/RUSTSEC-2021-0124 is still present in `main`

**Comment by jerryxwu** [comment]
@jaskij thanks again for the feedback. We are hoping to address these in an upcoming release soon.

**Comment by epgts** [comment]
After running `cargo update`, `cargo audit` reports two problems:

- serde_cbor is unmaintained - we're stuck until https://github.com/tcdi/pgx/issues/524 is resolved
- term_size is unmaintained - we just need to upgrade clap - PR #486 is a start, just two more after that

**Comment by epgts** [comment]
* PR #493 addresses `term_size`
* `cargo audit` now reports `xml-rs` as [unmaintained](https://rustsec.org/advisories/RUSTSEC-2022-0048), too.  This is yet another transitive dependency, this come coming through pgx and plist (itself coming to us through pgx).  Neither pgx nor plist seem to have open issues about it.

At the moment, the transitive issues are only "unmaintained" warnings, not actual problems, so not urgent.  However, deserialization code is generally rife with vulnerabilities, and we wouldn't want to be trying to rebase onto wildly different dependencies while under pressure of addressing a known vulnerability, so it would behoove us to get ahead of this.

**Comment by epgts** [comment]
Wow:  https://github.com/rustsec/advisory-db/issues/1121

**Comment by epgts** [comment]
With both these merged, we're down to just 3 warnings on transitive dependencies:
- https://github.com/timescale/timescaledb-toolkit/pull/492
- https://github.com/timescale/timescaledb-toolkit/pull/493

Thanks for the report!
