### ISSUE TITLE
Please match Timescaldb's supported PostgreSQL versions

### ISSUE THREAD

**Issue by jaskij** [timescale/timescaledb-toolkit#453]
## What's the functionality you would like to add ##

For `timescaledb-toolkit` to support the same PostgreSQL versions as TimescaleDB

## How would the function be used ##

---

## Why should this feature be added?  ##

Currently, there is a *very* long delay in the toolkit supporting PostgreSQL 14 - none of the released versions do, although Timescale itself has had that support [since 2.5.0 in October last year](https://docs.timescale.com/timescaledb/latest/overview/release-notes/#v2-3-1-2021-07-05).

### What scale is this useful at? ###

Any installation wanting to upgrade to PostgreSQL 14

## Drawbacks ##

It puts more stress on the maintainers to actually keep up to date.

## Open Questions ##

Are any questions we'd need to address before releasing this feature?

## Comments ##

After having written this issue, but before submitting, I have actually tried building and using 1.7.0 with PostgreSQL - to my surprise it actually works, at least as far as our project goes. But the README only lists versions the toolkit is tested against - and those only mention `pg12` and `pg13`, so it makes it seem as if `pg14` is not supported.

**Comment by jaskij** [comment]
@jerryxwu two points here:

There should be a separate section for supported versions. Or are you implying the toolkit isn't release ready yet, hence only the Testing section?

The [README at the tag *does not* list pg14](https://github.com/timescale/timescaledb-toolkit/blob/1.7.0/Readme.md) - that's what started this whole thing.

One more question from me then: does `timescaledb-toolkit` 1.7.0 support PostgreSQL 14 or not? You can't update the tag, but I can at least point the AUR maintainer to your answer so they can update their package.

**Comment by jerryxwu** [comment]
@jaskij Great points. Really appreciate your feedback.

**Comment by jerryxwu** [comment]
@jaskij Sorry just realized that I've missed your last question. 

> One more question from me then: does timescaledb-toolkit 1.7.0 support PostgreSQL 14 or not? 

Yes, PG 14 is supported.

**Comment by rtwalker** [comment]
closed by #463
