### ISSUE TITLE
Can't find toolkit download when installing with apt

### ISSUE THREAD

**Issue by arnorapsdnm** [timescale/timescaledb-toolkit#472]
System:
Debian 9.13
Postgres 12 with timescaledb

Issue:
root@debian:/home/test# apt install timescaledb-toolkit-postgresql-14
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package timescaledb-toolkit-postgresql-14 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'timescaledb-toolkit-postgresql-14' has no installation candidate

**Comment by rtwalker** [comment]
Hi @arnorapsdnm, thanks for your interest in the TimescaleDB Toolkit!

We currently only publish a packaged binary on Debian 11 Bullseye which explains why you're not finding an installation candidate. I'll discuss the possibility of building for your platform (it looks like TimescaleDB proper builds for Debian 9/10/11, so there's a good argument that we should too).

In the meantime, you'll have to build from source if you want to use the toolkit. If you encounter any trouble doing so, please report back here for assistance!

**Comment by zakjakub** [comment]
Installing from sources is not possible on servers with 4 GB RAM. 

So how to install timescaledb-toolkit on Debian 10?

**Comment by rtwalker** [comment]
Starting with our [1.11.0 release](https://github.com/timescale/timescaledb-toolkit/releases/tag/1.11.0) we've included support for pre-built binaries on Debian 10 with Postgres 12-14.  (Debian 9 has reached EOL since this issue was opened.)
