### ISSUE TITLE
Add update testing for timevector objects

### ISSUE THREAD

**Issue by WireBaron** [timescale/timescaledb-toolkit#494]
Our update test framework currently doesn't expose the version information we need to determine what objects we should be creating for the current iteration (so we don't try to create objects the version we're upgrading from).  We need to improve this so that we can automate the testing of timevector correctness over upgrades for the 1.10 release.

**Comment by thatzopoulos** [comment]
Resolved : https://github.com/timescale/timescaledb-toolkit/pull/558
