### ISSUE TITLE
`interpolated_delta` returns a `OrderError`

### ISSUE THREAD

**Issue by jledentu** [timescale/timescaledb-toolkit#499]
Hello 👋 

**Relevant system information:**
 - OS: MacOS 12.4 (running official [pg12-latest](https://hub.docker.com/layers/timescaledb-ha/timescale/timescaledb-ha/pg12-latest/images/sha256-5f08ee3014b5a75fbd971dcbad2ebfa798d6a1f040acc9b0fdcfb4d8712df801?context=explore))
 - PostgreSQL version (output of `SELECT version();`): 12
 - TimescaleDB Toolkit version (output of `\dx timescaledb_toolkit` in `psql`): 1.8.0
 - Installation method: docker

**Describe the bug**

When using `interpolated_delta`, I've got an error:

```
ERROR:  unable to add data to interpolation: OrderError
CONTEXT:  extension/src/counter_agg.rs:129:26
SQL state: XX000
```

Maybe I wrote the query incorrectly? Then query is quite simple though.

**To Reproduce**
1. Run `docker run -p 5432:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb-ha:pg12-latest`
2. Connect to the database
3. Enable the toolkit extension
4. Execute the queries below:

```sql
CREATE TABLE test (
	date timestamp with time zone NOT NULL,
    quantity double precision 
);

INSERT INTO test (date, quantity) VALUES
	('2022-01-01T00:00:00.00+00:00', 10),
	('2022-01-01T00:10:00.00+00:00', 11),
	('2022-01-01T00:20:00.00+00:00', 12),
	('2022-01-01T00:30:00.00+00:00', 16),
	('2022-01-01T00:40:00.00+00:00', 27),
	('2022-01-01T00:50:00.00+00:00', 0),
	('2022-01-01T01:00:00.00+00:00', 3),
	('2022-01-01T01:30:00.00+00:00', 5),
	('2022-01-01T01:50:00.00+00:00', 1),
	('2022-01-01T02:00:00.00+00:00', 6),
	('2022-01-01T02:10:00.00+00:00', 7),
	('2022-01-01T02:30:00.00+00:00', 8),
	('2022-01-01T03:00:00.00+00:00', 5),
	('2022-01-01T03:10:00.00+00:00', 10);
	
SELECT
    date,
    toolkit_experimental.interpolated_delta(
        summary,
        date,
        '30 min',
        LAG(summary) OVER (ORDER by date),
        LEAD(summary) OVER (ORDER by date)
    )
FROM (
    SELECT
        time_bucket('30 min'::interval, date) AS date,
        counter_agg(date, quantity) AS summary
    FROM test
    GROUP BY time_bucket('30 min'::interval, date)
) t;
```

**Expected behavior**
The `SELECT` is expected to return results without error.

**Actual behavior**
An error is returned:
```
ERROR:  unable to add data to interpolation: OrderError
CONTEXT:  extension/src/counter_agg.rs:129:26
SQL state: XX000
```

Thanks!

**Comment by WireBaron** [comment]
Thanks for the bug report @jledentu .  It looks like there's a logic error in interpolating the lower bound when the aggregate has a point at the minimum value for the bucket (and hence shouldn't need to interpolate).  We'll work on getting a fix for this in asap.
