### ISSUE TITLE
Accessors to retrieve first and last data points from TimeWeightSummary

### ISSUE THREAD

**Issue by jerryxwu** [timescale/timescaledb-toolkit#512]
Creating this issue for tracebility.

A user on [Stackoverflow](https://stackoverflow.com/questions/73475880/is-there-a-way-to-extract-start-and-end-from-a-timeweightsummary-timescaledb) asked to extract the first and the last point value and timestamp from a `time_weight` object.  We think it make sense to add the same accessors to `counter_agg` as well. There's very little risk of exposing the internal structure of the objects as the first and the last data points are needed for the `rollup` functions.

Specifically, the following accessors are discussed:

- `first_val` / `last_val`
- `first_time` / `last_time` (perhaps consider naming them as `first_at` / `last_at` to be consistent with `open_at`, `close_at`, etc.

**Comment by rtwalker** [comment]
> first_time / last_time (perhaps consider naming them as first_at / last_at to be consistent with open_at, close_at, etc.

This is a good point. Should we likewise consider `(first|last)` instead of `(first|last)_val`? Or are they too semantically different from the already existing [`first`](https://docs.timescale.com/api/latest/hyperfunctions/first/) and [`last`](https://docs.timescale.com/api/latest/hyperfunctions/last/) hyperfunctions?

**Comment by jerryxwu** [comment]
> Should we likewise consider (first|last) instead of (first|last)_val? Or are they too semantically different from the already existing [first](https://docs.timescale.com/api/latest/hyperfunctions/first/) and [last](https://docs.timescale.com/api/latest/hyperfunctions/last/) hyperfunctions?

Good point. I think it makes sense.
