### ISSUE TITLE
[Bug]: <LOCF has not correct behaviour>

### ISSUE THREAD

**Issue by emanuel-joos** [timescale/timescaledb-toolkit#544]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Other

### What happened?

I want is to apply time_weight with LOCF method in order to resample a time series. My original data looks like that: 

(‘timestemp’,’signal_id’, values) 
('2020-01-02T00:02:00', 6, 10);
('2020-01-02T00:55:00', 6, 100);
('2020-01-02T01:02:00', 6, 10);
('2020-01-02T01:55:00', 6, 100);
('2020-01-02T02:02:00', 6, 10);
('2020-01-02T02:55:00', 6, 100);
('2020-01-02T03:02:00', 6, 10);
.
.
.

What i am expecting from a time_weighted LOCF is the following: 

(‘timestemp’,’signal_id’, values)
 ('2020-01-02T01:00:00+00:00', 6,20,5),
 ('2020-01-02T02:00:00+00:00', 6,20,5),
 ('2020-01-02T03:00:00+00:00', 6,20,5),
 ('2020-01-02T04:00:00+00:00', 6,20.5),
 ('2020-01-02T05:00:00+00:00', 6,20.5),
 ('2020-01-02T06:00:00+00:00', 6,20.5),
.
.
.

This 20.5 results from the fact that the first 2 minutes the bucket has the value 100 then for 53 minutes the bucket has the value 10 and then for the last 5min it has the value 100 again.

so: (2*100 + 53*10 + 5*100)/60 = 20.5 

My query looks like that: 

    SELECT time_bucket('3600 s', ts,  '-3600 s'::INTERVAL) + '3600 s'  as interval, 
    signal_id, 
    average(time_weight('LOCF', ts, measurement_value)) as time_weighted_average 
    FROM measurements
    Where ts BETWEEN '2020-01-01' AND '2020-02-01'
    And signal_id in (6)
    GROUP BY signal_id, interval
    ORDER BY interval DESC;

What i get from that query is the following:

(‘timestemp’,’signal_id’, values)
 ('2020-01-02T01:00:00+00:00', 6,10),
 ('2020-01-02T02:00:00+00:00', 6,10),
 ('2020-01-02T03:00:00+00:00', 6,10),
 ('2020-01-02T04:00:00+00:00', 6,10),
 ('2020-01-02T05:00:00+00:00', 6,10),
 ('2020-01-02T06:00:00+00:00', 6,10),
.
.
.
Which is from my point of view not correct. I can see that the 100 (last element in the bucket) is ignored and also not carry on in the next bucket. 

### TimescaleDB version affected

2.8

### PostgreSQL version used

14.4

### What operating system did you use?

Mac OS X Montery M1

### What installation method did you use?

Docker

### What platform did you run on?

Managed Service for TimescaleDB (MST/Aiven)

### How can we reproduce the bug?

```bash
Take the dummy data and apply the query i posted
```

**Comment by davidkohn88** [comment]
These are Toolkit functions, so I've transferred over here!

**Comment by davidkohn88** [comment]
Can you please add which version of TimescaleDB Toolkit you are running, also, I believe this was solved with the `interpolated_average` experimental function we added in 1.10.1: https://docs.timescale.com/api/latest/hyperfunctions/time-weighted-averages/interpolated_average/ . 

The original issue was here: https://github.com/timescale/timescaledb-toolkit/issues/440
and the fix here: https://github.com/timescale/timescaledb-toolkit/pull/456

Let us know if that works for you, we'd love feedback on the experimental features as always!

**Comment by emanuel-joos** [comment]
Thanks you very much for your answer. I tried it but i can not get it to run. 

Here is my query: 

```
SELECT
    signal_id,
    time_value,
    interpolated_average(
        tws,
        time_value,
        '{resampled_interval} s',
        LAG(tws) OVER (ORDER BY time_value Partition By signal_id),
        LEAD(tws) OVER (ORDER BY time_value Partition By signal_id)
    ) 
    FROM (
    SELECT
        signal_id,
        time_bucket('{resampled_interval} s', ts) AS time_value,
        time_weight('LOCF', ts, measurement_value) AS tws
    FROM measurements
    Where ts BETWEEN '{datetime_from}' AND '{datetime_to}'
    And signal_id in ({signals})    
    GROUP BY signal_id, time_value
    ) t
```

There error i am getting is: 
**psycopg2.errors.SyntaxError: syntax error at or near "Partition"
E           LINE 11:          Partition By signal_id),**

For local testing i am using the *timescale/timescaledb-ha:pg14-latest* image. I think there the newest  TimescaleDB Toolkit is running.

**Comment by lservini** [comment]
hey @emanuel-joos may you try to switch order:
```
LAG(tws) OVER (Partition By signal_id ORDER BY time_value),
LEAD(tws) OVER (Partition By signal_id ORDER BY time_value)
```
and let me know?

Thanks

**Comment by emanuel-joos** [comment]
Query looks like that now. 
```
SELECT signal_id, time_value, 
    interpolated_average(
        tws,
        time_value,
        '{resampled_interval} s',
        LAG(tws) OVER (Partition By signal_id ORDER BY time_value),
        LEAD(tws) OVER (Partition By signal_id ORDER BY time_value)
    ) 
    FROM (
    SELECT
        signal_id,
        time_bucket('{resampled_interval} s', ts) AS time_value,
        time_weight('LOCF', ts, measurement_value) AS tws
    FROM measurements
    Where ts BETWEEN '{datetime_from}' AND '{datetime_to}'
    And signal_id in ({signals})    
    GROUP BY signal_id, time_value
    ) t
```

But now i get the error: 
**
E           LINE 3:     interpolated_average(
E                       ^
E           HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
**

**Comment by lservini** [comment]
@emanuel-joos 
change
```
SELECT signal_id, time_value, 
    interpolated_average(
```
with
```
SELECT
    signal_id,
    time_value,
    toolkit_experimental.interpolated_average(
```

**Comment by emanuel-joos** [comment]
Already tried that as well. It is not working. On the latest image and also on the managed service.

**Comment by lservini** [comment]
@emanuel-joos 
that's strange, it work on my instance:
```
SELECT
    signal_id,
    time_value,
    toolkit_experimental.interpolated_average(
        tws,
        time_value,
        '3600 s',
        LAG(tws) OVER (Partition By signal_id ORDER BY time_value),
        LEAD(tws) OVER (Partition By signal_id ORDER BY time_value)
    ) 
    FROM (
    SELECT
        signal_id,
        time_bucket('3600 s', ts) AS time_value,
        time_weight('LOCF', ts, measurement_value) AS tws
    FROM measurements
    Where ts BETWEEN '2022-08-25' AND '2022-09-15'
    And signal_id = 9    
    GROUP BY signal_id, time_value
    ) t
limit 10;
signal_id |       time_value       | interpolated_average 
-----------+------------------------+----------------------
         9 | 2022-08-25 00:00:00+00 |    51.15435477286926
         9 | 2022-08-25 01:00:00+00 |   49.622770738293525
         9 | 2022-08-25 02:00:00+00 |     49.4993975044186
         9 | 2022-08-25 03:00:00+00 |   49.931869247731356
         9 | 2022-08-25 04:00:00+00 |    49.76338847142343
         9 | 2022-08-25 05:00:00+00 |    50.95823467155786
         9 | 2022-08-25 06:00:00+00 |      50.526272782591
         9 | 2022-08-25 07:00:00+00 |   49.291729005453966
         9 | 2022-08-25 08:00:00+00 |    50.07228322132271
         9 | 2022-08-25 09:00:00+00 |    49.33625558235949
(10 rows)
```

What toolkit version do you have? You can see it with 
```
\dx
```
Also, may you give a try using **psql** and in case it doesn't work try to set **seach_path**:
```
set search_path = "$user", public, toolkit_experimental;
```

Thanks

**Comment by emanuel-joos** [comment]
i have: 
 timescaledb_toolkit | 1.7.0   | public     | Library of analytical hyperfunctions, time-series pipelining, and other SQL utilities

I tried 
`set search_path = "$user", public, toolkit_experimental;`

but it is still not working. 

Thank you

**Comment by emanuel-joos** [comment]
Using **psql**  is also not working showing the same error.

**Comment by emanuel-joos** [comment]
I can see it is timescaledb_toolkit | 1.7.0 but you mentioned i need 1.10.1 how do i update that on manged Services ? Since 

`ALTER EXTENSION timescaledb_toolkit UPDATE;`

gives me: 

*Version 1.7.0 of extension "timescaledb_toolkit" is already installed*

**Comment by lservini** [comment]
hi @emanuel-joos any update?

**Comment by emanuel-joos** [comment]
Hey @lservini 

update just finished during the night and it worked. I have now the newest version. So i think we can close this one. 

I opened another issue https://github.com/timescale/timescaledb-toolkit/issues/548 considering the interpolate_average.
