### ISSUE TITLE
Signal Heartbeat Claculation

### ISSUE THREAD

**Issue by emanuel-joos** [timescale/timescaledb-toolkit#578]
## Situation
We have about 71'000 signals coming from different power plants. Sometimes the connection to one of the power plant is lost. In order to realize that the connection was lost for each power plant we defined so called "heartbeat" signals, where we know we should get values at least every 10 seconds. 

## Dummy example 
timestamp, signal_id, value 
'2020-01-01T00:00:00', 9, 10
'2020-01-01T00:10:00', 9, 10;
'2020-01-01T00:20:00', 9, 10;
'2020-01-01T00:30:00', 9, 10;
'2020-01-01T00:40:00', 9, 10;
'2020-01-01T00:50:00', 9, 10;
'2020-01-01T01:00:00', 9, 10;
'2020-01-01T01:50:00', 9, 20;
'2020-01-01T02:00:00', 9, 20;
'2020-01-01T02:10:00', 9, 20;
'2020-01-01T02:20:00', 9, 20;
'2020-01-01T02:30:00', 9, 20;
'2020-01-01T02:40:00', 9, 20);
...

Now we say, signal 9 is our heartbeat signal and at least every 10 minute we should get a value otherwise the connection is broken. 

Our expected heartbeat query output should be something like that: 

ts_start_valid, ts_end_valid
'2020-01-01T00:00:00', '2020-01-01T01:00:00'
'2020-01-01T01:50:00', '2020-01-01T02:40:00'
....

## Workaround 
We created a workaround query with a materialized view

```
CREATE MATERIALIZED VIEW heartbeats_powerplant1 AS
with t1 as (
Select
ts,
ts - lag(ts,1) over (ORDER BY ts) as diff,
ts - lead(ts,1) over (ORDER BY ts) as diff_negative
From measurements
Where signal_id in (9)
),
t2 as (
select row_number() over (order by ts ) as id,
    ts as start_valid
    from t1 where (diff > '10 minutes' or diff is Null)
),
t3 as (
select row_number() over (order by ts ) as id,
ts as end_valid
    from t1 where (diff_negative < '- 10 minutes' or diff_negative is Null)
),
t4 as (
Select start_valid, end_valid from t2
FULL outer Join t3 on t2.id=t3.id
)
select * from t4;
``` 

## Problem we are facing with that materialized view
Since we have a lot of data the query takes about 7min and if we want to refresh the materialized view every 15min we ran into problem. Now we have seen the (CREATE MATERIALIZED VIEW (Continuous Aggregate)  from the timescale toolkid but the problem is, that we don't have a time bucketing function in our query.  

It would be nice to have a materialzed view if refresh is triggerd only the new data is taken into consideration.

**Comment by jerryxwu** [comment]
@emanuel-joos thank you for reaching out. You are correct that [Continuous Aggregate](https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/about-continuous-aggregates/) might potentially be something useful to you. It is one of the core benefits of [Timescale](https://www.timescale.com/products#benefits) offering. I'm thinking you could perhaps approximate what you are looking for by first time_bucketing the signals into "1 minute" buckets. That way, it's not exactly 10 minutes but close?

BTW, time_bucket is actually built right into [TimescaleDB](https://github.com/timescale/timescaledb).

**Comment by emanuel-joos** [comment]
@jerryxwu Thanks for your answer. 10min was just a dummy example, we need something like 60 seconds. And we need it exact, not approximately. What we really need is something like the postgres materialized view but but without bucketing and something we can update every 15min. So it should run max. 30 seconds and not almost 10 minutes.

**Comment by davidkohn88** [comment]
So, as I understand it, you're trying to find any gap in the data that's larger than a certain value, so we could actually develop an aggregate...something like `heartbeat_agg(timestamp, max_allowed_gap)`. You could then extract live zones and dead zones with an accessor, which could either return the start and end times like you have above or a tstzrange or the like...

You could rollup or have the interpolating accessors like with other of our functions in order to look back across time bucket boundaries. This would then allow you to use this in a continuous aggregate.
