### ISSUE TITLE
Postgres 15 support

### ISSUE THREAD

**Issue by jerryxwu** [timescale/timescaledb-toolkit#579]
Postgres 15 has just been released on Oct 13. The toolkit needs to add support for it at the same time as TimescaleDB. Otherwise, we won't be able to roll PG 15 support to Timescale Cloud as it needs both TimescaleDB and Toolkit. This has several steps:

- [x] Upgrade to pgx 0.5 - this is a prerequisite for a 0.5.x with PG 15 support: #547 
- [x] Contribute upstream to pgx for PG 15 support: https://github.com/tcdi/pgx/pull/729
- [ ] Upgrade to 0.5.x with PG 15 support

**Comment by Smittyvb** [comment]
We added support for Postgres 15 in 1.13.1, closing.
