### ISSUE TITLE
Postgres 15 ubi8

### ISSUE THREAD

**Issue by nimbit-software** [timescale/timescaledb-toolkit#689]
**Is your feature request related to a problem? Please describe.**
I would like to install toolkit with postgres 15 on ubi8  but the package does not seam to be available 

microdnf  install -y timescaledb-toolkit-postgresql-15  

error: No package matches 'timescaledb-toolkit-postgresql-15'

I image the package has not been officially deployed yet. 

**Describe the solution you'd like**
A clear and concise description of what you would like to happen.

**Describe alternatives you've considered**

**Additional context**

**Comment by Smittyvb** [comment]
I just pushed the RPMs for 1.13.1 to packagecloud – you should be able to install `timescaledb-toolkit-postgresql-15` now. Let me know if you run into any problems with them.

Thanks for reporting this!

**Comment by tonyalaribe** [comment]
Seems timescaledb-toolkit-postgresql-16 is missing as well.  What can I do to get that up as well?
