### ISSUE TITLE
Stabilize Heartbeat Aggregate

### ISSUE THREAD

**Issue by WireBaron** [timescale/timescaledb-toolkit#717]
## Heartbeat Agg

**What evidence do we have the feature is being used**

It looks like there is only minimal use of this feature on customer systems.

**Why do we feel this feature is ready to be stable**

This is a fairly straightforward feature that we're confident is useful.

**Is there any known further work needed on this feature after stabilization**

No

**Are there any compatibility concerns that may arise during future work on this feature**

No

### Feature History
- Experimental release version: 1.13.0
- Last version modifying on-disk format: 1.13.0
- Target stabilization version: 1.15.0

### Stabilization checklist:
- [x] Ensure tests exist for all public API
- [ ] Ensure API documentation exists and is accurate
- [x] Remove `toolkit_experimental` tags and update test usages
- [x] Add arrow operators for accessors if applicable
- [x] Ensure arrow operators have test coverage
- [x] If present, ensure `combine` and `rollup` are tested
- [x] Add serialization tests for on disk format
- [x] Add serialization tests for text format
- [x] Add upgrade tests
- [x] Add continuous aggregate test
- [ ] Add feature level documentation

**Comment by jerryxwu** [comment]
Based on our recent experience, I'd suggest that we add at least one extensive example in the doc as part of the stabilization.
