### ISSUE TITLE
Unable to install timescaledb-toolkit via homebrew; SHA256 mismatch

### ISSUE THREAD

**Issue by michaelwiktorek** [timescale/timescaledb-toolkit#757]
**Relevant system information:**
 - OS: MacOS Ventura 13.3.1, M1 max (ARM) chip
 - Installation method: homebrew

**Describe the bug**
When following the instructions provided in the [Timescale Docs](https://docs.timescale.com/self-hosted/latest/tooling/install-toolkit/) for installing Toolkit on macOS, the homebrew installation failed at the step `brew install timescaledb-toolkit` with a SHA256 mismatch.

**To Reproduce**
1. run `brew tap timescale/tap`
2. run `brew update`
3. run `brew install timescaledb-toolkit`
4. Receive `Error: timescaledb-toolkit: SHA256 mismatch` instead of successfully installing the package.

**Expected behavior**
I expect the package to be installed.

**Actual behavior**
Received this full error:
```
.........
==> Fetching timescale/tap/timescaledb-toolkit
==> Downloading https://github.com/tcdi/pgx/archive/refs/tags/v0.7.1.tar.gz
==> Downloading from https://codeload.github.com/tcdi/pgrx/tar.gz/refs/tags/v0.7.1
# #=O#- #
Error: timescaledb-toolkit: SHA256 mismatch
Expected: 8615ad8497cf2bf9f50faf2f2e495f2c6fefa935d70414fc21a29dc8c6256754
  Actual: 71f44407760cd8b8bf4d8cd20964b26f11b815653b99978147b7bd0a482a39b5
    File: /Users/[my_username]/Library/Caches/Homebrew/downloads/5006eb8a6ad9d580cf1def141162253cf3566eae7ddfdf99ca5397ecbe2e9629--pgrx-0.7.1.tar.gz
To retry an incomplete download, remove the file above.
```

**Additional context**
This is happening on an M1 mac running macOS Ventura 13.3.1. As the error text suggested, I removed the file and attempted the install again a few times, and always received the same results, so it doesn't feel like a one-off issue with a corrupted download. I also tried `brew cleanup && brew upgrade` and they did not fix the issue.

**Comment by michaelwiktorek** [comment]
Upon further examination, via `brew edit timescaledb-toolkit`, it looks like the mismatch is specific to the `cargo-pgx` resource in the homebrew formula. 
```
resource "cargo-pgx" do
    url "https://github.com/tcdi/pgx/archive/refs/tags/v0.7.1.tar.gz"
    sha256 "8615ad8497cf2bf9f50faf2f2e495f2c6fefa935d70414fc21a29dc8c6256754"
  end
```

**Comment by syvb** [comment]
One of our dependencies [renamed itself](https://github.com/tcdi/pgrx/issues/1106), which makes archive generated by GitHub change, even though the contents have not. I opened a PR to update the hash at https://github.com/timescale/homebrew-tap/pull/38.
