### ISSUE TITLE
State aggregation (state_agg) for multiple devices/systems in multiple states

### ISSUE THREAD

**Issue by rohitmurali97** [timescale/timescaledb-toolkit#758]
State aggregation is currently supported for state tracking of one particular system in the table. 
However, in a case where there are multiple systems/devices, having a set of states, there might be a need to track state changes and durations in a particular state for a specific device. Currently, the arguments for state_agg are timestamp and value of the state and it returns StateAgg 'object' which contains details about the state changes.

The solution to this problem would be to add the system or device or identifier field to the original state_agg function as an argument which would then be a field in the calculated StateAgg 'object'.

An alternate for this would be to write custom function which does the same and would have 2 steps :
1. Get list of system identifiers
2. Loop over system identifiers and run the state_agg function along with necessary accessors for every identifier.

![timescale](https://user-images.githubusercontent.com/41644816/235374987-12c7bc55-fc61-427d-b59e-68258a2ca1d0.JPG)

**Comment by WireBaron** [comment]
I think a simpler alternative would be something like the following, given a table device_state(id, state):

```SQL
SELECT id, state_agg(state)
FROM device_state
GROUP BY id;
```

Let us know if this is inadequate for your case.
