### ISSUE TITLE
Segmentation fault when running min_n max_n on big data set

### ISSUE THREAD

**Issue by oddfrost** [timescale/timescaledb-toolkit#759]
**Relevant system information:**
 - OS: alma linux 8.7
 - PostgreSQL version: 14.7
 - TimescaleDB Toolkit version: 1.16.0
 - Installation method: timescaledb repo, self hosted package

**Describe the bug**
Postgres crashes when executing query like 
select 
min_n(metric, 2)
from table;

Data set (1 000 000+ rows)
In postgres log i can see message: server process was terminated by signal 11: Segmentation fault. 

**To Reproduce**
CREATE TABLE public.test("time" timestamptz NOT NULL, duration int4 NULL);

SELECT create_hypertable('test', 'time');

Do $$
Begin 
For r in 1..1000000 loop
Insert into test values(now() + (r||'s')::interval, r);
end loop;
End;
$$;

Select min_n(duration, 2) from test;

**Expected behavior**
Get result with smallest numbers (1, 2)

**Actual behavior**
Process crushes with segmentation fault (but it works on small data sets, with four rows).

**Comment by oddfrost** [comment]
May be related to

https://github.com/timescale/timescaledb-toolkit/issues/755

**Comment by jerryxwu** [comment]
@oddfrost thank you for reporting the issue. I have reproduced the issue that you've experienced. We'll consider fixing it in an upcoming release.

**Comment by jerryxwu** [comment]
@oddfrost If you haven't noticed yet, the fix has been included in the latest [1.17.0](https://github.com/timescale/timescaledb-toolkit/releases/tag/1.17.0) release.
