### ISSUE TITLE
Rate/Delta Aggs

### ISSUE THREAD

**Issue by davidkohn88** [timescale/timescaledb-toolkit#8]
Prometheus and other timeseries databases provide several convenience functions for calculating the rate of change of certain values over time, while some of this behavior can be accomplished in Timescale, it's significantly more cumbersome, and, as you start getting into some of the more complex versions of the behavior, it becomes significantly more difficult to calculate these values without custom aggregates. 

In addition, for the use of Promscale and an eventual PromQL to SQL converter, we wish to be able to re-produce the behavior of some common PromQL functions. 

Note that Prometheus has two different types of metrics that this class of functions acts on: 
- counters, which are assumed to be always increasing, and if they ever decrease are assumed to have "reset" and are actually still increasing in reality so the previous value is added on (see #4). 
- gauges, which measure something instantaneously at a certain level without respect to their previous states (ie they are non additive and do not reset)

Prometheus provides the following functions: 
  - `increase` = the difference between a counter's value at the beginning and end of a bucket accounting for any resets and extrapolating to the edges of the bucket (when possible?). (This must provide a non-negative value).
  - `delta` = the difference between a gauge's first and last value in a bucket (unlcear whether it extrapolates or not)
  - `rate` = the rate of change of a counter, it accounts for any counter reset events inside a bucket, extrapolates to its edges and then calculates a per second rate of change (ie `increase(value)/ increase(time)`, like increase, this must produce a non-negative value)
  - `deriv` = the rate of change of a gauge, it doesn't do any counter reset logic, and calculates the per second rate of change based on a linear regression
  - `irate` = the instantaneous rate of change derived from the final two points in a bucket
  - `idelta` = the instantaneous delta derived from the final two points in a bucket.
  

One can reproduce much of this functionality with Timescale functions like first/last and other bits, but it would be rather difficult to do most of efficiently and without writing custom aggregates. This is especially true if you want to use them in continuous aggregates where otherwise things get very weird.
  
It would be great to provide some similar functionality, both to be able to re-create these Prometheus functions as well as to enable similar use cases and to make them play nicely with continuous aggs.

**Comment by JLockerman** [comment]
With respect to Prometheus extrapolation https://github.com/prometheus/prometheus/issues/3746 might be interesting

**Comment by epgts** [comment]
All done but `deriv`, now covered by #391.
