### ISSUE TITLE
Timescale 2.17 / Postgresql 17 support

### ISSUE THREAD

**Issue by gabrielstellini** [timescale/timescaledb-toolkit#813]
**Describe the solution you'd like**

Are there plans to have postgresql-17 support for timescaledb-toolkit?

https://packagecloud.io/app/timescale/timescaledb/search?dist=&filter=all&page=2&q=postgresql-17

The docs point to here when referring to hyperfunctions, but there are no packages matching timescaledb-toolkit-postgresql-17.

**Comment by iliyas86** [comment]
if there's a tentative timeline or plan for when the toolkit will support PostgreSQL 17. We're currently planning to upgrade to PostgreSQL 17 and would like to know if there are any upcoming releases or near-term plans to provide compatibility.

Any information or insights would be greatly appreciated!

**Comment by Jo0** [comment]
Looks like there's a WIP PR right now! 🤞 

#816

**Comment by Jo0** [comment]
I feel like I'm pretty close with this PR #819. No idea who I should get in contact with to resolve some GH Actions stuff.

**Comment by skreborn** [comment]
#819 and #824 are now merged. Does this complete PostgreSQL 17 support?

**Comment by gabrielstellini** [comment]
I don't think so, since there hasn't been a release yet

**Comment by psztoch** [comment]
Do not forget about arm64 architecture packages for Debian.

**Comment by gabrielstellini** [comment]
1.19.0 released!
I see both an arm64 and an amd64 build, so I'm closing the issue

https://github.com/timescale/timescaledb-toolkit/releases/tag/1.19.0
