### ISSUE TITLE
Docs TOC broken

### ISSUE THREAD

**Issue by JLockerman** [timescale/timescaledb-toolkit#99]
The links at the bottom of the docs Readme doesn't work.

**Comment by davidkohn88** [comment]
Lots of links in our docs including ones inside of many of the pages don't seem to work, it might be related to the dashes in the links...something we should figure out and fix before stabilization I think...

**Comment by inselbuch** [comment]
Once time-weighted averages are available, will this be possible?

CREATE MATERIALIZED VIEW tptest WITH (timescaledb.continuous)
AS
select time_bucket('1 hour', time) as bucket, tagname, TIME_WEIGHTED_AVERAGE(value) as "TWAValue"
from MYTABLE [with columns, time, value]
group by 1,2;

**Comment by davidkohn88** [comment]
Hey @inselbuch a) I think this may not be the place for this convo, do you want to ask in the Q & A forum in discussions? https://github.com/timescale/timescale-analytics/discussions/categories/q-a?discussions_q=time_weighted+category%3AQ%26A

b) yes, and time weighted averages are available (though the API is a bit different than you're assuming here), in the experimental schema for now, which means you have to set a special flag to use them in continuous aggregates, but that is possible and there's an [example in the docs](https://github.com/timescale/timescale-analytics/blob/main/extension/docs/time_weighted_average.md#example-usage-) of how to do that and also re-aggregate on top of that.

**Comment by epgts** [comment]
These docs are no longer user-facing.
